// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp32_p4_eye_factory

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenCamera
void ui_ScreenCamera_screen_init(void);
lv_obj_t * ui_ScreenCamera;
lv_obj_t * ui_PanelCanvas;
lv_obj_t * ui_ImageCanvasSelect;
lv_obj_t * ui_ImageCanvasUp;
lv_obj_t * ui_ImageCanvasDown;
lv_obj_t * ui_PanelCanvasMaskLarge;
lv_obj_t * ui_PanelCanvasPopupCamera;
lv_obj_t * ui_LabelPanelCanvasPopupCameraTop;
lv_obj_t * ui_PanelCanvasPopupAICamera;
lv_obj_t * ui_LabelPanelCanvasPopupAICameraTop;
lv_obj_t * ui_PanelCanvasPopupAICameraLine;
lv_obj_t * ui_LabelPanelCanvasPopupAICameraDown;
lv_obj_t * ui_PanelCanvasPopupCameraLine;
lv_obj_t * ui_LabelPanelCanvasPopupCameraDown;
lv_obj_t * ui_ImageCanvasNOSDcard;
lv_obj_t * ui_ImageCanvasSDcard;
lv_obj_t * ui_ImageCanvasMenu;
lv_obj_t * ui_LabelCanvas2X;
lv_obj_t * ui_LabelCanvas3X;
lv_obj_t * ui_LabelCanvasFactor;
lv_obj_t * ui_PanelCanvasMaskCamera;
lv_obj_t * ui_ImagePanelCanvasMaskCamera;
lv_obj_t * ui_PanelCanvasMaskAICamera;
lv_obj_t * ui_ImagePanelCanvasMaskAICamera;
lv_obj_t * ui_PanelCanvasPopupCameraInterval;
lv_obj_t * ui_LabelPanelCanvasPopupCameraTopInterval;
lv_obj_t * ui_PanelCanvasPopupCameraIntervalLine;
lv_obj_t * ui_LabelPanelCanvasPopupCameraIntervalDown;
lv_obj_t * ui_PanelCanvasMaskCameraInterval;
lv_obj_t * ui_ImagePanelCanvasMaskCameraInterval;
lv_obj_t * ui_LabelCanvas5mplus;
lv_obj_t * ui_LabelCanvas5mSub;
lv_obj_t * ui_LabelCanvasInvervalTime;
lv_obj_t * ui_PanelCanvasPopupVideoMode;
lv_obj_t * ui_LabelPanelCanvasPopupVideoModeTop;
lv_obj_t * ui_PanelCanvasPopupVideoModeLine;
lv_obj_t * ui_LabelPanelCanvasPopupVideoModeDown;
lv_obj_t * ui_PanelCanvasMaskVideoMode;
lv_obj_t * ui_ImagePanelCanvasMaskVideoMode;
lv_obj_t * ui_PanelCanvasPopupSDWarning;
lv_obj_t * ui_LabelPanelCanvasPopupSDWarning;
lv_obj_t * ui_PanelCanvasPopupCameraSDWarning;
lv_obj_t * ui_LabelPanelCanvasPopupCameraSDWarning;
lv_obj_t * ui_PanelCanvasPopupIntervalTimerWarning;
lv_obj_t * ui_LabelPanelCanvasPopupIntervalTimerWarning;
lv_obj_t * ui_PanelCanvasPopupCameraIntervalTimerWarning;
lv_obj_t * ui_LabelPanelCanvasPopupCameraIntervalTimerWarning;
lv_obj_t * ui_LabelPanelCanvasPopupIntervalTimer;
lv_obj_t * ui_PanelCanvasPopupIntervalTimerWarningEnd;
lv_obj_t * ui_LabelPanelCanvasPopupIntervalTimerWarningEnd;
lv_obj_t * ui_PanelCanvasPopupCameraIntervalTimerWarningEnd;
lv_obj_t * ui_LabelPanelCanvasPopupCameraIntervalTimerWarningEnd;
lv_obj_t * ui_LabelPanelCanvasPopupIntervalTimerEnd;
lv_obj_t * ui_ImageRedDot;
lv_obj_t * ui_LabelRedDotTime;
lv_obj_t * ui_PanelSettings;
lv_obj_t * ui_PanelPanelSettingsGyroscope;
lv_obj_t * ui_LabelPanelPanelSettingsGyroscopeItem;
lv_obj_t * ui_LabelPanelPanelSettingsGyroscopeBody;
lv_obj_t * ui_LabelPanelSettings;
lv_obj_t * ui_PanelPanelSettingsLanguage;
lv_obj_t * ui_LabelPanelPanelSettingsODItem;
lv_obj_t * ui_LabelPanelPanelSettingsODBody;
lv_obj_t * ui_PanelPanelSettingsRes;
lv_obj_t * ui_LabelPanelPanelSettingsResItem;
lv_obj_t * ui_LabelPanelPanelSettingsResBody;
lv_obj_t * ui_PanelPanelSettingsFlash;
lv_obj_t * ui_LabelPanelPanelSettingsFlashItem;
lv_obj_t * ui_LabelPanelPanelSettingsFlashBody;
lv_obj_t * ui_PanelSettingsMenu;
lv_obj_t * ui_LabelPanelSettingsMenu;
lv_obj_t * ui_PanelInrervalTimePrompt;
lv_obj_t * ui_LabelPanelInrervalTimePrompt;
lv_obj_t * ui_LabelPanelInrervalTimePromptMin;
lv_obj_t * ui_PanelCameraSettings;
lv_obj_t * ui_PanelPanelSettingsContrast;
lv_obj_t * ui_LabelPanelPanelSettingsContrast;
lv_obj_t * ui_SliderPanelPanelSettingsContrast;
lv_obj_t * ui_PanelPanelSettingsSaturation;
lv_obj_t * ui_LabelPanelPanelSettingsSaturation;
lv_obj_t * ui_SliderPanelPanelSettingsSaturation;
lv_obj_t * ui_PanelPanelSettingsBrightness;
lv_obj_t * ui_LabelPanelPanelSettingsBrightness;
lv_obj_t * ui_SliderPanelPanelSettingsBrightness;
lv_obj_t * ui_PanelPanelSettingsHue;
lv_obj_t * ui_LabelPanelPanelSettingsHue;
lv_obj_t * ui_SliderPanelPanelSettingsHue;
lv_obj_t * ui_PanelCanvasPopupSDSpaceWarning;
lv_obj_t * ui_LabelPanelCanvasPopupSDSpaceWarning;
lv_obj_t * ui_PanelCanvasPopupCameraSDSpaceWarning;
lv_obj_t * ui_LabelPanelCanvasPopupCameraSDSpaceWarning;


// SCREEN: ui_ScreenAlbum
void ui_ScreenAlbum_screen_init(void);
lv_obj_t * ui_ScreenAlbum;
lv_obj_t * ui_ImageScreenAlbum;
lv_obj_t * ui_ImageAlbumMenu;
lv_obj_t * ui_ImageAlbumUp;
lv_obj_t * ui_ImageAlbumDown;
lv_obj_t * ui_PanelImageScreenAlbumDelete;
lv_obj_t * ui_LabelPanelImageScreenAlbumDelete;
lv_obj_t * ui_ButtonPanelImageScreenAlbumDeleteYES;
lv_obj_t * ui_LabelButtonPanelImageScreenAlbumDeleteYES;
lv_obj_t * ui_ButtonPanelImageScreenAlbumDeleteNO;
lv_obj_t * ui_LabelButtonPanelImageScreenAlbumDeleteNO;
lv_obj_t * ui_PanelAlbumPopupSDWarning;
lv_obj_t * ui_LabelPanelAlbumPopupSDWarning;
lv_obj_t * ui_PanelAlbumPopupCameraSDWarning;
lv_obj_t * ui_LabelPanelAlbumPopupCameraSDWarning;


// SCREEN: ui_ScreenUSB
void ui_ScreenUSB_screen_init(void);
lv_obj_t * ui_ScreenUSB;
lv_obj_t * ui_ImageScreenUSB;
lv_obj_t * ui_ImageScreenUSBSuccess;
lv_obj_t * ui_ImageScreenUSBWarning;
lv_obj_t * ui_ImageUSBNOSDcard;


// SCREEN: ui_ScreenPicSave
void ui_ScreenPicSave_screen_init(void);
lv_obj_t * ui_ScreenPicSave;
lv_obj_t * ui_ImageScreenPicSaveAlbum;
lv_obj_t * ui_ImageScreenPicSaveCamera;
lv_obj_t * ui_ImageScreenPicSaveIntervalCam;
lv_obj_t * ui_ImageScreenPicSaveVideoMode;
lv_obj_t * ui_ImageScreenPicSaveUSB;
lv_obj_t * ui_ImageScreenPicSaveSetting;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_usb_page[2] = {&ui_img_usb_page1_png, &ui_img_usb_page2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenCamera_screen_init();
    ui_ScreenAlbum_screen_init();
    ui_ScreenUSB_screen_init();
    ui_ScreenPicSave_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenCamera);
}
