// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp32_p4_eye_factory

#ifndef _ESP32_P4_EYE_FACTORY_UI_H
#define _ESP32_P4_EYE_FACTORY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenCamera
void ui_ScreenCamera_screen_init(void);
extern lv_obj_t * ui_ScreenCamera;
extern lv_obj_t * ui_PanelCanvas;
extern lv_obj_t * ui_ImageCanvasSelect;
extern lv_obj_t * ui_ImageCanvasUp;
extern lv_obj_t * ui_ImageCanvasDown;
extern lv_obj_t * ui_PanelCanvasMaskLarge;
extern lv_obj_t * ui_PanelCanvasPopupCamera;
extern lv_obj_t * ui_PanelCanvasPopupAICamera;
extern lv_obj_t * ui_LabelPanelCanvasPopupAICameraTop;
extern lv_obj_t * ui_PanelCanvasPopupAICameraLine;
extern lv_obj_t * ui_LabelPanelCanvasPopupAICameraDown;
extern lv_obj_t * ui_LabelPanelCanvasPopupCameraTop;
extern lv_obj_t * ui_PanelCanvasPopupCameraLine;
extern lv_obj_t * ui_LabelPanelCanvasPopupCameraDown;
extern lv_obj_t * ui_ImageCanvasNOSDcard;
extern lv_obj_t * ui_ImageCanvasSDcard;
extern lv_obj_t * ui_ImageCanvasMenu;
extern lv_obj_t * ui_LabelCanvas2X;
extern lv_obj_t * ui_LabelCanvas3X;
extern lv_obj_t * ui_LabelCanvasFactor;
extern lv_obj_t * ui_PanelCanvasMaskCamera;
extern lv_obj_t * ui_ImagePanelCanvasMaskCamera;
extern lv_obj_t * ui_PanelCanvasMaskAICamera;
extern lv_obj_t * ui_ImagePanelCanvasMaskAICamera;
extern lv_obj_t * ui_PanelCanvasPopupCameraInterval;
extern lv_obj_t * ui_LabelPanelCanvasPopupCameraTopInterval;
extern lv_obj_t * ui_PanelCanvasPopupCameraIntervalLine;
extern lv_obj_t * ui_LabelPanelCanvasPopupCameraIntervalDown;
extern lv_obj_t * ui_PanelCanvasMaskCameraInterval;
extern lv_obj_t * ui_ImagePanelCanvasMaskCameraInterval;
extern lv_obj_t * ui_LabelCanvas5mplus;
extern lv_obj_t * ui_LabelCanvas5mSub;
extern lv_obj_t * ui_LabelCanvasInvervalTime;
extern lv_obj_t * ui_PanelCanvasPopupVideoMode;
extern lv_obj_t * ui_LabelPanelCanvasPopupVideoModeTop;
extern lv_obj_t * ui_PanelCanvasPopupVideoModeLine;
extern lv_obj_t * ui_LabelPanelCanvasPopupVideoModeDown;
extern lv_obj_t * ui_PanelCanvasMaskVideoMode;
extern lv_obj_t * ui_ImagePanelCanvasMaskVideoMode;
extern lv_obj_t * ui_PanelCanvasPopupSDWarning;
extern lv_obj_t * ui_LabelPanelCanvasPopupSDWarning;
extern lv_obj_t * ui_PanelCanvasPopupCameraSDWarning;
extern lv_obj_t * ui_LabelPanelCanvasPopupCameraSDWarning;
extern lv_obj_t * ui_PanelCanvasPopupIntervalTimerWarning;
extern lv_obj_t * ui_LabelPanelCanvasPopupIntervalTimerWarning;
extern lv_obj_t * ui_PanelCanvasPopupCameraIntervalTimerWarning;
extern lv_obj_t * ui_LabelPanelCanvasPopupCameraIntervalTimerWarning;
extern lv_obj_t * ui_LabelPanelCanvasPopupIntervalTimer;
extern lv_obj_t * ui_PanelCanvasPopupIntervalTimerWarningEnd;
extern lv_obj_t * ui_LabelPanelCanvasPopupIntervalTimerWarningEnd;
extern lv_obj_t * ui_PanelCanvasPopupCameraIntervalTimerWarningEnd;
extern lv_obj_t * ui_LabelPanelCanvasPopupCameraIntervalTimerWarningEnd;
extern lv_obj_t * ui_LabelPanelCanvasPopupIntervalTimerEnd;
extern lv_obj_t * ui_ImageRedDot;
extern lv_obj_t * ui_LabelRedDotTime;
extern lv_obj_t * ui_PanelSettings;
extern lv_obj_t * ui_LabelPanelSettings;
extern lv_obj_t * ui_PanelPanelSettingsGyroscope;
extern lv_obj_t * ui_LabelPanelPanelSettingsGyroscopeItem;
extern lv_obj_t * ui_LabelPanelPanelSettingsGyroscopeBody;
extern lv_obj_t * ui_PanelPanelSettingsLanguage;
extern lv_obj_t * ui_LabelPanelPanelSettingsODItem;
extern lv_obj_t * ui_LabelPanelPanelSettingsODBody;
extern lv_obj_t * ui_PanelPanelSettingsRes;
extern lv_obj_t * ui_LabelPanelPanelSettingsResItem;
extern lv_obj_t * ui_LabelPanelPanelSettingsResBody;
extern lv_obj_t * ui_PanelPanelSettingsFlash;
extern lv_obj_t * ui_LabelPanelPanelSettingsFlashItem;
extern lv_obj_t * ui_LabelPanelPanelSettingsFlashBody;
extern lv_obj_t * ui_PanelSettingsMenu;
extern lv_obj_t * ui_LabelPanelSettingsMenu;
extern lv_obj_t * ui_PanelInrervalTimePrompt;
extern lv_obj_t * ui_LabelPanelInrervalTimePrompt;
extern lv_obj_t * ui_LabelPanelInrervalTimePromptMin;
extern lv_obj_t * ui_PanelCameraSettings;
extern lv_obj_t * ui_PanelPanelSettingsContrast;
extern lv_obj_t * ui_LabelPanelPanelSettingsContrast;
extern lv_obj_t * ui_SliderPanelPanelSettingsContrast;
extern lv_obj_t * ui_PanelPanelSettingsSaturation;
extern lv_obj_t * ui_LabelPanelPanelSettingsSaturation;
extern lv_obj_t * ui_SliderPanelPanelSettingsSaturation;
extern lv_obj_t * ui_PanelPanelSettingsBrightness;
extern lv_obj_t * ui_LabelPanelPanelSettingsBrightness;
extern lv_obj_t * ui_SliderPanelPanelSettingsBrightness;
extern lv_obj_t * ui_PanelPanelSettingsHue;
extern lv_obj_t * ui_LabelPanelPanelSettingsHue;
extern lv_obj_t * ui_SliderPanelPanelSettingsHue;
extern lv_obj_t * ui_PanelCanvasPopupSDSpaceWarning;
extern lv_obj_t * ui_LabelPanelCanvasPopupSDSpaceWarning;
extern lv_obj_t * ui_PanelCanvasPopupCameraSDSpaceWarning;
extern lv_obj_t * ui_LabelPanelCanvasPopupCameraSDSpaceWarning;

// SCREEN: ui_ScreenAlbum
void ui_ScreenAlbum_screen_init(void);
extern lv_obj_t * ui_ScreenAlbum;
extern lv_obj_t * ui_ImageScreenAlbum;
extern lv_obj_t * ui_ImageAlbumMenu;
extern lv_obj_t * ui_ImageAlbumUp;
extern lv_obj_t * ui_ImageAlbumDown;
extern lv_obj_t * ui_PanelImageScreenAlbumDelete;
extern lv_obj_t * ui_LabelPanelImageScreenAlbumDelete;
extern lv_obj_t * ui_ButtonPanelImageScreenAlbumDeleteYES;
extern lv_obj_t * ui_LabelButtonPanelImageScreenAlbumDeleteYES;
extern lv_obj_t * ui_ButtonPanelImageScreenAlbumDeleteNO;
extern lv_obj_t * ui_LabelButtonPanelImageScreenAlbumDeleteNO;
extern lv_obj_t * ui_PanelAlbumPopupSDWarning;
extern lv_obj_t * ui_LabelPanelAlbumPopupSDWarning;
extern lv_obj_t * ui_PanelAlbumPopupCameraSDWarning;
extern lv_obj_t * ui_LabelPanelAlbumPopupCameraSDWarning;
// SCREEN: ui_ScreenUSB
void ui_ScreenUSB_screen_init(void);
extern lv_obj_t * ui_ScreenUSB;
extern lv_obj_t * ui_ImageScreenUSB;
extern lv_obj_t * ui_ImageScreenUSBSuccess;
extern lv_obj_t * ui_ImageScreenUSBWarning;
extern lv_obj_t * ui_ImageUSBNOSDcard;
// SCREEN: ui_ScreenPicSave
void ui_ScreenPicSave_screen_init(void);
extern lv_obj_t * ui_ScreenPicSave;
extern lv_obj_t * ui_ImageScreenPicSaveAlbum;
extern lv_obj_t * ui_ImageScreenPicSaveCamera;
extern lv_obj_t * ui_ImageScreenPicSaveIntervalCam;
extern lv_obj_t * ui_ImageScreenPicSaveVideoMode;
extern lv_obj_t * ui_ImageScreenPicSaveUSB;
extern lv_obj_t * ui_ImageScreenPicSaveSetting;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_button_select_png);    // assets/button_select.png
LV_IMG_DECLARE(ui_img_up_button_png);    // assets/up_button.png
LV_IMG_DECLARE(ui_img_button_down_png);    // assets/button_down.png
LV_IMG_DECLARE(ui_img_sdcard_no_png);    // assets/sdcard_no.png
LV_IMG_DECLARE(ui_img_sdcard_yes_png);    // assets/sdcard_yes.png
LV_IMG_DECLARE(ui_img_button_menu_png);    // assets/button_menu.png
LV_IMG_DECLARE(ui_img_camera_small_png);    // assets/camera_small.png
LV_IMG_DECLARE(ui_img_interval_small_png);    // assets/interval_small.png
LV_IMG_DECLARE(ui_img_video_small_png);    // assets/video_small.png
LV_IMG_DECLARE(ui_img_reddot_recording_png);    // assets/reddot_recording.png
LV_IMG_DECLARE(ui_img_usb_page1_png);    // assets/usb_page1.png
LV_IMG_DECLARE(ui_img_usb_page2_png);    // assets/usb_page2.png
LV_IMG_DECLARE(ui_img_usb_page_warning_png);    // assets/usb_page_warning.png
LV_IMG_DECLARE(ui_img_album_big_png);    // assets/album_big.png
LV_IMG_DECLARE(ui_img_camera_big_png);    // assets/camera_big.png
LV_IMG_DECLARE(ui_img_interval_big_png);    // assets/interval_big.png
LV_IMG_DECLARE(ui_img_video_big_png);    // assets/video_big.png
LV_IMG_DECLARE(ui_img_usb_big_png);    // assets/usb_big.png
LV_IMG_DECLARE(ui_img_settings_big_png);    // assets/settings_big.png
LV_IMG_DECLARE(ui_img_ai_detect_png); // assets/ai_detect.png
LV_IMG_DECLARE(ui_img_ai_detect_small_png); // assets/ai_detect_small.png


LV_FONT_DECLARE(ui_font_FontKoHoBold14);
LV_FONT_DECLARE(ui_font_FontKoHoBold18);
LV_FONT_DECLARE(ui_font_FontKoHoBold28);
LV_FONT_DECLARE(ui_font_FontKoHoMiniBold14);
LV_FONT_DECLARE(ui_font_FontKoHoMiniBold18);
LV_FONT_DECLARE(ui_font_FontKoHoMiniBold22);
LV_FONT_DECLARE(ui_font_FontKoHoMiniBold24);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
