// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: UI_Setting

#include "../ui.h"

void ui_ScreenSettingAbout_screen_init(void)
{
ui_ScreenSettingAbout = lv_obj_create(NULL);
lv_obj_set_style_bg_color(ui_ScreenSettingAbout, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenSettingAbout, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelScreenSettingAboutList = lv_obj_create(ui_ScreenSettingAbout);
lv_obj_set_width( ui_PanelScreenSettingAboutList, lv_pct(88));
lv_obj_set_height( ui_PanelScreenSettingAboutList, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PanelScreenSettingAboutList, 43 );
lv_obj_set_y( ui_PanelScreenSettingAboutList, 77 );
lv_obj_set_flex_flow(ui_PanelScreenSettingAboutList,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanelScreenSettingAboutList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_PanelScreenSettingAboutList, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_radius(ui_PanelScreenSettingAboutList, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpinnerScreenAboutList = lv_spinner_create(ui_ScreenSettingAbout,1000,90);
lv_obj_set_width( ui_SpinnerScreenAboutList, lv_pct(16));
lv_obj_set_height( ui_SpinnerScreenAboutList, lv_pct(16));
lv_obj_set_align( ui_SpinnerScreenAboutList, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SpinnerScreenAboutList, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_SpinnerScreenAboutList, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_width(ui_SpinnerScreenAboutList, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_SpinnerScreenAboutList, lv_color_hex(0xC2C2C2), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SpinnerScreenAboutList, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SpinnerScreenAboutList, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_ButtonScreenSettingAboutReturn = lv_btn_create(ui_ScreenSettingAbout);
lv_obj_set_width( ui_ButtonScreenSettingAboutReturn, 60);
lv_obj_set_height( ui_ButtonScreenSettingAboutReturn, 60);
lv_obj_set_x( ui_ButtonScreenSettingAboutReturn, -352 );
lv_obj_set_y( ui_ButtonScreenSettingAboutReturn, -596 );
lv_obj_set_align( ui_ButtonScreenSettingAboutReturn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonScreenSettingAboutReturn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonScreenSettingAboutReturn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonScreenSettingAboutReturn, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonScreenSettingAboutReturn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageScreenSettingAboutReturn = lv_img_create(ui_ButtonScreenSettingAboutReturn);
lv_img_set_src(ui_ImageScreenSettingAboutReturn, &ui_img_return_png);
lv_obj_set_width( ui_ImageScreenSettingAboutReturn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageScreenSettingAboutReturn, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ImageScreenSettingAboutReturn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageScreenSettingAboutReturn, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageScreenSettingAboutReturn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_ImageScreenSettingAboutReturn, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageScreenSettingAboutReturn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageScreenSettingAbout = lv_img_create(ui_ScreenSettingAbout);
lv_img_set_src(ui_ImageScreenSettingAbout, &ui_img_482951309);
lv_obj_set_width( ui_ImageScreenSettingAbout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageScreenSettingAbout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageScreenSettingAbout, -21 );
lv_obj_set_y( ui_ImageScreenSettingAbout, -446 );
lv_obj_set_align( ui_ImageScreenSettingAbout, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageScreenSettingAbout, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageScreenSettingAbout, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PanelScreenSettingAbout = lv_obj_create(ui_ScreenSettingAbout);
lv_obj_set_width( ui_PanelScreenSettingAbout, 752);
lv_obj_set_height( ui_PanelScreenSettingAbout, 588);
lv_obj_set_x( ui_PanelScreenSettingAbout, 0 );
lv_obj_set_y( ui_PanelScreenSettingAbout, 33 );
lv_obj_set_align( ui_PanelScreenSettingAbout, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelScreenSettingAbout,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanelScreenSettingAbout, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_PanelScreenSettingAbout, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PanelPanelScreenSettingAbout = lv_obj_create(ui_PanelScreenSettingAbout);
lv_obj_set_width( ui_PanelPanelScreenSettingAbout, 716);
lv_obj_set_height( ui_PanelPanelScreenSettingAbout, 82);
lv_obj_set_x( ui_PanelPanelScreenSettingAbout, 53 );
lv_obj_set_y( ui_PanelPanelScreenSettingAbout, 915 );
lv_obj_set_align( ui_PanelPanelScreenSettingAbout, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPanelScreenSettingAbout, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelPanelScreenSettingAbout, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPanelScreenSettingAbout, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAboutDevice = lv_label_create(ui_PanelPanelScreenSettingAbout);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAboutDevice, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAboutDevice, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAboutDevice, -252 );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAboutDevice, 1 );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAboutDevice, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAboutDevice,"Device Name");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAboutDevice, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAbout2 = lv_label_create(ui_PanelPanelScreenSettingAbout);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAbout2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAbout2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAbout2, 227 );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAbout2, -1 );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAbout2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAbout2,"ESP32-P4");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAbout2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPanelScreenSettingAbout1 = lv_obj_create(ui_PanelScreenSettingAbout);
lv_obj_set_width( ui_PanelPanelScreenSettingAbout1, 716);
lv_obj_set_height( ui_PanelPanelScreenSettingAbout1, 82);
lv_obj_set_x( ui_PanelPanelScreenSettingAbout1, 1 );
lv_obj_set_y( ui_PanelPanelScreenSettingAbout1, -15 );
lv_obj_set_align( ui_PanelPanelScreenSettingAbout1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPanelScreenSettingAbout1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelPanelScreenSettingAbout1, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPanelScreenSettingAbout1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAboutManufacturer = lv_label_create(ui_PanelPanelScreenSettingAbout1);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAboutManufacturer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAboutManufacturer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAboutManufacturer, -252 );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAboutManufacturer, 1 );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAboutManufacturer, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAboutManufacturer,"Manufacturer");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAboutManufacturer, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAbout1 = lv_label_create(ui_PanelPanelScreenSettingAbout1);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAbout1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAbout1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAbout1, 233 );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAbout1, -2 );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAbout1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAbout1,"ESPRESSIF");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAbout1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPanelScreenSettingAbout2 = lv_obj_create(ui_PanelScreenSettingAbout);
lv_obj_set_width( ui_PanelPanelScreenSettingAbout2, 716);
lv_obj_set_height( ui_PanelPanelScreenSettingAbout2, 82);
lv_obj_set_x( ui_PanelPanelScreenSettingAbout2, 1 );
lv_obj_set_y( ui_PanelPanelScreenSettingAbout2, -15 );
lv_obj_set_align( ui_PanelPanelScreenSettingAbout2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPanelScreenSettingAbout2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelPanelScreenSettingAbout2, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPanelScreenSettingAbout2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAboutMAC = lv_label_create(ui_PanelPanelScreenSettingAbout2);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAboutMAC, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAboutMAC, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAboutMAC, -306 );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAboutMAC, 1 );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAboutMAC, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAboutMAC,"MAC");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAboutMAC, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAbout3 = lv_label_create(ui_PanelPanelScreenSettingAbout2);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAbout3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAbout3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAbout3, 233 );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAbout3, -2 );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAbout3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAbout3,"---------------");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAbout3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPanelScreenSettingAbout3 = lv_obj_create(ui_PanelScreenSettingAbout);
lv_obj_set_width( ui_PanelPanelScreenSettingAbout3, 716);
lv_obj_set_height( ui_PanelPanelScreenSettingAbout3, 82);
lv_obj_set_x( ui_PanelPanelScreenSettingAbout3, 1 );
lv_obj_set_y( ui_PanelPanelScreenSettingAbout3, -15 );
lv_obj_set_align( ui_PanelPanelScreenSettingAbout3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPanelScreenSettingAbout3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelPanelScreenSettingAbout3, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPanelScreenSettingAbout3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAboutUIFramework = lv_label_create(ui_PanelPanelScreenSettingAbout3);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAboutUIFramework, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAboutUIFramework, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAboutUIFramework, -250 );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAboutUIFramework, 2 );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAboutUIFramework, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAboutUIFramework,"UI Framework");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAboutUIFramework, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAbout4 = lv_label_create(ui_PanelPanelScreenSettingAbout3);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAbout4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAbout4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAbout4, 227 );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAbout4, 0 );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAbout4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAbout4,"ESP32_UI");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAbout4, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPanelScreenSettingAbout4 = lv_obj_create(ui_PanelScreenSettingAbout);
lv_obj_set_width( ui_PanelPanelScreenSettingAbout4, 716);
lv_obj_set_height( ui_PanelPanelScreenSettingAbout4, 82);
lv_obj_set_x( ui_PanelPanelScreenSettingAbout4, 1 );
lv_obj_set_y( ui_PanelPanelScreenSettingAbout4, -15 );
lv_obj_set_align( ui_PanelPanelScreenSettingAbout4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPanelScreenSettingAbout4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelPanelScreenSettingAbout4, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPanelScreenSettingAbout4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAboutSoftwareVersion = lv_label_create(ui_PanelPanelScreenSettingAbout4);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAboutSoftwareVersion, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAboutSoftwareVersion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAboutSoftwareVersion, -236 );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAboutSoftwareVersion, 2 );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAboutSoftwareVersion, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAboutSoftwareVersion,"Software Version");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAboutSoftwareVersion, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAbout5 = lv_label_create(ui_PanelPanelScreenSettingAbout4);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAbout5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAbout5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAbout5, 235 );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAbout5, -2 );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAbout5, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAbout5,"---------------");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAbout5, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPanelScreenSettingAbout5 = lv_obj_create(ui_PanelScreenSettingAbout);
lv_obj_set_width( ui_PanelPanelScreenSettingAbout5, 716);
lv_obj_set_height( ui_PanelPanelScreenSettingAbout5, 82);
lv_obj_set_x( ui_PanelPanelScreenSettingAbout5, 1 );
lv_obj_set_y( ui_PanelPanelScreenSettingAbout5, -15 );
lv_obj_set_align( ui_PanelPanelScreenSettingAbout5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPanelScreenSettingAbout5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelPanelScreenSettingAbout5, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPanelScreenSettingAbout5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion = lv_label_create(ui_PanelPanelScreenSettingAbout5);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion, -205 );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion, 2 );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion,"UI Framework Version");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAbout6 = lv_label_create(ui_PanelPanelScreenSettingAbout5);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAbout6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAbout6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAbout6, 235 );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAbout6, -2 );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAbout6, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAbout6,"---------------");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAbout6, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ButtonScreenSettingAboutReturn, ui_event_ButtonScreenSettingAboutReturn, LV_EVENT_ALL, NULL);

}
