// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: UI_Setting

#include "../ui.h"

void ui_ScreenSettingWiFi_screen_init(void)
{
ui_ScreenSettingWiFi = lv_obj_create(NULL);
lv_obj_set_style_bg_color(ui_ScreenSettingWiFi, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenSettingWiFi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelScreenSettingWiFiSwitch = lv_obj_create(ui_ScreenSettingWiFi);
lv_obj_set_height( ui_PanelScreenSettingWiFiSwitch, 83);
lv_obj_set_width( ui_PanelScreenSettingWiFiSwitch, lv_pct(90));
lv_obj_set_x( ui_PanelScreenSettingWiFiSwitch, 43 );
lv_obj_set_y( ui_PanelScreenSettingWiFiSwitch, 77 );
lv_obj_clear_flag( ui_PanelScreenSettingWiFiSwitch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelScreenSettingWiFiSwitch, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImagePanelScreenSettingWiFiSwitch = lv_img_create(ui_PanelScreenSettingWiFiSwitch);
lv_img_set_src(ui_ImagePanelScreenSettingWiFiSwitch, &ui_img_wifi_png);
lv_obj_set_width( ui_ImagePanelScreenSettingWiFiSwitch, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelScreenSettingWiFiSwitch, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelScreenSettingWiFiSwitch, 3 );
lv_obj_set_x( ui_ImagePanelScreenSettingWiFiSwitch, lv_pct(1) );
lv_obj_set_align( ui_ImagePanelScreenSettingWiFiSwitch, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImagePanelScreenSettingWiFiSwitch, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelScreenSettingWiFiSwitch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelScreenSettingWiFiSwitch = lv_label_create(ui_PanelScreenSettingWiFiSwitch);
lv_obj_set_width( ui_LabelPanelScreenSettingWiFiSwitch, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelScreenSettingWiFiSwitch, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_LabelPanelScreenSettingWiFiSwitch, 0 );
lv_obj_set_x( ui_LabelPanelScreenSettingWiFiSwitch, lv_pct(10) );
lv_obj_set_align( ui_LabelPanelScreenSettingWiFiSwitch, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LabelPanelScreenSettingWiFiSwitch,"Wi-Fi");
lv_obj_set_style_text_font(ui_LabelPanelScreenSettingWiFiSwitch, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SwitchPanelScreenSettingWiFiSwitch = lv_switch_create(ui_PanelScreenSettingWiFiSwitch);
lv_obj_set_width( ui_SwitchPanelScreenSettingWiFiSwitch, 50);
lv_obj_set_height( ui_SwitchPanelScreenSettingWiFiSwitch, 25);
lv_obj_set_y( ui_SwitchPanelScreenSettingWiFiSwitch, 1 );
lv_obj_set_x( ui_SwitchPanelScreenSettingWiFiSwitch, lv_pct(89) );
lv_obj_set_align( ui_SwitchPanelScreenSettingWiFiSwitch, LV_ALIGN_LEFT_MID );


ui_PanelScreenSettingWiFiList = lv_obj_create(ui_ScreenSettingWiFi);
lv_obj_set_width( ui_PanelScreenSettingWiFiList, lv_pct(88));
lv_obj_set_height( ui_PanelScreenSettingWiFiList, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PanelScreenSettingWiFiList, 25 );
lv_obj_set_y( ui_PanelScreenSettingWiFiList, 119 );
lv_obj_set_flex_flow(ui_PanelScreenSettingWiFiList,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanelScreenSettingWiFiList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_PanelScreenSettingWiFiList, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_radius(ui_PanelScreenSettingWiFiList, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpinnerScreenSettingWiFi = lv_spinner_create(ui_ScreenSettingWiFi,1000,90);
lv_obj_set_width( ui_SpinnerScreenSettingWiFi, lv_pct(16));
lv_obj_set_height( ui_SpinnerScreenSettingWiFi, lv_pct(16));
lv_obj_set_align( ui_SpinnerScreenSettingWiFi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SpinnerScreenSettingWiFi, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_SpinnerScreenSettingWiFi, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_width(ui_SpinnerScreenSettingWiFi, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_SpinnerScreenSettingWiFi, lv_color_hex(0xC2C2C2), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SpinnerScreenSettingWiFi, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SpinnerScreenSettingWiFi, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_ButtonScreenSettingWiFiReturn = lv_btn_create(ui_ScreenSettingWiFi);
lv_obj_set_width( ui_ButtonScreenSettingWiFiReturn, 60);
lv_obj_set_height( ui_ButtonScreenSettingWiFiReturn, 60);
lv_obj_set_x( ui_ButtonScreenSettingWiFiReturn, -352 );
lv_obj_set_y( ui_ButtonScreenSettingWiFiReturn, -596 );
lv_obj_set_align( ui_ButtonScreenSettingWiFiReturn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonScreenSettingWiFiReturn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonScreenSettingWiFiReturn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonScreenSettingWiFiReturn, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonScreenSettingWiFiReturn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageScreenSettingWiFiReturn = lv_img_create(ui_ButtonScreenSettingWiFiReturn);
lv_img_set_src(ui_ImageScreenSettingWiFiReturn, &ui_img_return_png);
lv_obj_set_width( ui_ImageScreenSettingWiFiReturn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageScreenSettingWiFiReturn, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ImageScreenSettingWiFiReturn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageScreenSettingWiFiReturn, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageScreenSettingWiFiReturn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_ImageScreenSettingWiFiReturn, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageScreenSettingWiFiReturn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ButtonScreenSettingWiFiReturn, ui_event_ButtonScreenSettingWiFiReturn, LV_EVENT_ALL, NULL);

}
