/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Gesture

#ifndef UI_GESTUREDETECTSCREEN_H
#define UI_GESTUREDETECTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GestureDetectScreen
extern void ui_GestureDetectScreen_screen_init(void);
extern void ui_GestureDetectScreen_screen_destroy(void);
extern lv_obj_t *ui_GestureDetectScreen;
extern lv_obj_t *ui_ButtonContainer;
extern lv_obj_t *ui_ShakePanel;
extern lv_obj_t *ui_ShakeLabel;
extern void ui_event_ShakeSwitch(lv_event_t *e);
extern lv_obj_t *ui_ShakeSwitch;
extern lv_obj_t *ui_RollPanel;
extern lv_obj_t *ui_RollLabel;
extern void ui_event_RollSwitch(lv_event_t *e);
extern lv_obj_t *ui_RollSwitch;
extern lv_obj_t *ui_AxisContainer;
extern lv_obj_t *ui_AxisXLine;
extern lv_obj_t *ui_AxisYLine;
extern lv_obj_t *ui_AxisZLine;
extern lv_obj_t *ui_AxisXArrow1;
extern lv_obj_t *ui_AxisXArrow2;
extern lv_obj_t *ui_AxisYArrow1;
extern lv_obj_t *ui_AxisYArrow2;
extern lv_obj_t *ui_AxisZArrow1;
extern lv_obj_t *ui_AxisZArrow2;
extern lv_obj_t *ui_AxisXLabel;
extern lv_obj_t *ui_AxisYLabel;
extern lv_obj_t *ui_AxisZLabel;
extern lv_obj_t *ui_AxisXLine;
extern lv_obj_t *ui_AxisYLine;
extern lv_obj_t *ui_AxisZLine;
extern lv_obj_t *ui_AxisXArrow1;
extern lv_obj_t *ui_AxisXArrow2;
extern lv_obj_t *ui_AxisYArrow1;
extern lv_obj_t *ui_AxisYArrow2;
extern lv_obj_t *ui_AxisZArrow1;
extern lv_obj_t *ui_AxisZArrow2;
extern lv_obj_t *ui_AxisXLabel;
extern lv_obj_t *ui_AxisYLabel;
extern lv_obj_t *ui_AxisZLabel;
extern lv_obj_t *ui_StatusContainer;
extern lv_obj_t *ui_PickupPanel;
extern lv_obj_t *ui_PickupStatusLight;
extern lv_obj_t *ui_PickupLabel;
extern lv_obj_t *ui_PutdownPanel;
extern lv_obj_t *ui_PutdownStatusLight;
extern lv_obj_t *ui_PutdownLabel;
extern lv_obj_t *ui_ImageContainer;
extern lv_obj_t *ui_SuccessImage;
extern lv_obj_t *ui_GestureImage;
extern lv_obj_t *ui_ReadyLabel;
extern lv_obj_t *ui_MotionDetectedLabel;
extern lv_obj_t *ui_GestureDetailLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
