/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Gesture

#ifndef UI_GESTUREDETECTTIPSCREEN_H
#define UI_GESTUREDETECTTIPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GestureDetectTipScreen
extern void ui_GestureDetectTipScreen_screen_init(void);
extern void ui_GestureDetectTipScreen_screen_destroy(void);
extern lv_obj_t *ui_GestureDetectTipScreen;
extern lv_obj_t *ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
