/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Gesture

#include "../ui.h"
#include "../ui_app.h"

lv_obj_t *ui_GestureDetectScreen = NULL;
lv_obj_t *ui_ButtonContainer = NULL;
lv_obj_t *ui_ShakePanel = NULL;
lv_obj_t *ui_ShakeLabel = NULL;
lv_obj_t *ui_ShakeSwitch = NULL;
lv_obj_t *ui_RollPanel = NULL;
lv_obj_t *ui_RollLabel = NULL;
lv_obj_t *ui_RollSwitch = NULL;
lv_obj_t *ui_AxisContainer = NULL;
lv_obj_t *ui_AxisXLine = NULL;
lv_obj_t *ui_AxisYLine = NULL;
lv_obj_t *ui_AxisZLine = NULL;
lv_obj_t *ui_AxisXArrow1 = NULL;
lv_obj_t *ui_AxisXArrow2 = NULL;
lv_obj_t *ui_AxisYArrow1 = NULL;
lv_obj_t *ui_AxisYArrow2 = NULL;
lv_obj_t *ui_AxisZArrow1 = NULL;
lv_obj_t *ui_AxisZArrow2 = NULL;
lv_obj_t *ui_AxisXLabel = NULL;
lv_obj_t *ui_AxisYLabel = NULL;
lv_obj_t *ui_AxisZLabel = NULL;
lv_obj_t *ui_StatusContainer = NULL;
lv_obj_t *ui_PickupPanel = NULL;
lv_obj_t *ui_PickupStatusLight = NULL;
lv_obj_t *ui_PickupLabel = NULL;
lv_obj_t *ui_PutdownPanel = NULL;
lv_obj_t *ui_PutdownStatusLight = NULL;
lv_obj_t *ui_PutdownLabel = NULL;
lv_obj_t *ui_ImageContainer = NULL;
lv_obj_t *ui_SuccessImage = NULL;
lv_obj_t *ui_GestureImage = NULL;
lv_obj_t *ui_ReadyLabel = NULL;
lv_obj_t *ui_MotionDetectedLabel = NULL;
lv_obj_t *ui_GestureDetailLabel = NULL;

void ui_GestureDetectScreen_screen_init(void)
{
    ui_GestureDetectScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_GestureDetectScreen, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_GestureDetectScreen, lv_color_hex(0xDCC7E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GestureDetectScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonContainer = lv_obj_create(ui_GestureDetectScreen);
    lv_obj_remove_style_all(ui_ButtonContainer);
    lv_obj_set_width(ui_ButtonContainer, 105);
    lv_obj_set_height(ui_ButtonContainer, 200);
    lv_obj_set_x(ui_ButtonContainer, -80);
    lv_obj_set_y(ui_ButtonContainer, -5);
    lv_obj_set_align(ui_ButtonContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ButtonContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_ButtonContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Shake Panel
    ui_ShakePanel = lv_obj_create(ui_ButtonContainer);
    lv_obj_set_width(ui_ShakePanel, 90);
    lv_obj_set_height(ui_ShakePanel, 55);
    lv_obj_set_align(ui_ShakePanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ShakePanel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_ShakePanel, lv_color_hex(0x968BE4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShakePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShakeLabel = lv_label_create(ui_ShakePanel);
    lv_obj_set_width(ui_ShakeLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_ShakeLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_ShakeLabel, -2);
    lv_obj_set_y(ui_ShakeLabel, -15);
    lv_obj_set_align(ui_ShakeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShakeLabel, "Shake");

    ui_ShakeSwitch = lv_obj_create(ui_ShakePanel);
    lv_obj_set_width(ui_ShakeSwitch, 25);
    lv_obj_set_height(ui_ShakeSwitch, 25);
    lv_obj_set_x(ui_ShakeSwitch, 0);
    lv_obj_set_y(ui_ShakeSwitch, 8);
    lv_obj_set_align(ui_ShakeSwitch, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ShakeSwitch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_ShakeSwitch, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ShakeSwitch, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShakeSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ShakeSwitch, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ShakeSwitch, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    // Axis Indicator Container
    ui_AxisContainer = lv_obj_create(ui_ButtonContainer);
    lv_obj_set_width(ui_AxisContainer, 120);
    lv_obj_set_height(ui_AxisContainer, 85);
    lv_obj_set_x(ui_AxisContainer, -10);
    lv_obj_set_y(ui_AxisContainer, 50);
    lv_obj_set_align(ui_AxisContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AxisContainer, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_opa(ui_AxisContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AxisContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_AxisContainer, LV_OBJ_FLAG_OVERFLOW_VISIBLE);

    // Origin point (center of axes)
#define ORIGIN_X 60
#define ORIGIN_Y 40

    // X-axis: Left-down arrow - shortened to ensure full visibility
    static const lv_point_precise_t x_line_points[] = {{ORIGIN_X, ORIGIN_Y}, {ORIGIN_X - 20, ORIGIN_Y + 12}};
    ui_AxisXLine = lv_line_create(ui_AxisContainer);
    lv_line_set_points(ui_AxisXLine, x_line_points, 2);
    lv_obj_set_style_line_color(ui_AxisXLine, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_AxisXLine, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_remove_flag(ui_AxisXLine, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // X-axis arrow head - vertical arrow pointing upward from the line end
    static const lv_point_precise_t x_arrow1_points[] = {{ORIGIN_X - 20, ORIGIN_Y + 15}, {ORIGIN_X - 20, ORIGIN_Y + 7}};
    ui_AxisXArrow1 = lv_line_create(ui_AxisContainer);
    lv_line_set_points(ui_AxisXArrow1, x_arrow1_points, 2);
    lv_obj_set_style_line_color(ui_AxisXArrow1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_AxisXArrow1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_remove_flag(ui_AxisXArrow1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // Horizontal line at arrow end to form arrowhead
    static const lv_point_precise_t x_arrow2_points[] = {{ORIGIN_X - 20, ORIGIN_Y + 14}, {ORIGIN_X - 14, ORIGIN_Y + 14}};
    ui_AxisXArrow2 = lv_line_create(ui_AxisContainer);
    lv_line_set_points(ui_AxisXArrow2, x_arrow2_points, 2);
    lv_obj_set_style_line_color(ui_AxisXArrow2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_AxisXArrow2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_remove_flag(ui_AxisXArrow2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // X-axis label
    ui_AxisXLabel = lv_label_create(ui_AxisContainer);
    lv_label_set_text(ui_AxisXLabel, "X");
    lv_obj_set_style_text_color(ui_AxisXLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(ui_AxisXLabel, ORIGIN_X - 32, ORIGIN_Y - 2);
    lv_obj_remove_flag(ui_AxisXLabel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // Y-axis: Right arrow - extended to ensure visibility, dark green color
    static const lv_point_precise_t y_line_points[] = {{ORIGIN_X, ORIGIN_Y}, {ORIGIN_X + 32, ORIGIN_Y}};
    ui_AxisYLine = lv_line_create(ui_AxisContainer);
    lv_line_set_points(ui_AxisYLine, y_line_points, 2);
    lv_obj_set_style_line_color(ui_AxisYLine, lv_color_hex(0x008000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_AxisYLine, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_remove_flag(ui_AxisYLine, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // Y-axis arrow head
    static const lv_point_precise_t y_arrow1_points[] = {{ORIGIN_X + 30, ORIGIN_Y}, {ORIGIN_X + 27, ORIGIN_Y - 3}};
    ui_AxisYArrow1 = lv_line_create(ui_AxisContainer);
    lv_line_set_points(ui_AxisYArrow1, y_arrow1_points, 2);
    lv_obj_set_style_line_color(ui_AxisYArrow1, lv_color_hex(0x008000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_AxisYArrow1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_remove_flag(ui_AxisYArrow1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    static const lv_point_precise_t y_arrow2_points[] = {{ORIGIN_X + 30, ORIGIN_Y}, {ORIGIN_X + 27, ORIGIN_Y + 3}};
    ui_AxisYArrow2 = lv_line_create(ui_AxisContainer);
    lv_line_set_points(ui_AxisYArrow2, y_arrow2_points, 2);
    lv_obj_set_style_line_color(ui_AxisYArrow2, lv_color_hex(0x008000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_AxisYArrow2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_remove_flag(ui_AxisYArrow2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // Y-axis label
    ui_AxisYLabel = lv_label_create(ui_AxisContainer);
    lv_label_set_text(ui_AxisYLabel, "Y");
    lv_obj_set_style_text_color(ui_AxisYLabel, lv_color_hex(0x008000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(ui_AxisYLabel, ORIGIN_X + 32, ORIGIN_Y - 8);
    lv_obj_remove_flag(ui_AxisYLabel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // Z-axis: Up arrow - longer arrow
    static const lv_point_precise_t z_line_points[] = {{ORIGIN_X, ORIGIN_Y}, {ORIGIN_X, ORIGIN_Y - 30}};
    ui_AxisZLine = lv_line_create(ui_AxisContainer);
    lv_line_set_points(ui_AxisZLine, z_line_points, 2);
    lv_obj_set_style_line_color(ui_AxisZLine, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_AxisZLine, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_remove_flag(ui_AxisZLine, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // Z-axis arrow head
    static const lv_point_precise_t z_arrow1_points[] = {{ORIGIN_X, ORIGIN_Y - 30}, {ORIGIN_X - 3, ORIGIN_Y - 25}};
    ui_AxisZArrow1 = lv_line_create(ui_AxisContainer);
    lv_line_set_points(ui_AxisZArrow1, z_arrow1_points, 2);
    lv_obj_set_style_line_color(ui_AxisZArrow1, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_AxisZArrow1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_remove_flag(ui_AxisZArrow1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    static const lv_point_precise_t z_arrow2_points[] = {{ORIGIN_X, ORIGIN_Y - 30}, {ORIGIN_X + 3, ORIGIN_Y - 25}};
    ui_AxisZArrow2 = lv_line_create(ui_AxisContainer);
    lv_line_set_points(ui_AxisZArrow2, z_arrow2_points, 2);
    lv_obj_set_style_line_color(ui_AxisZArrow2, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_AxisZArrow2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_remove_flag(ui_AxisZArrow2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // Z-axis label
    ui_AxisZLabel = lv_label_create(ui_AxisContainer);
    lv_label_set_text(ui_AxisZLabel, "Z");
    lv_obj_set_style_text_color(ui_AxisZLabel, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(ui_AxisZLabel, ORIGIN_X - 15, ORIGIN_Y - 35);
    lv_obj_remove_flag(ui_AxisZLabel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // Roll Panel (top)
    ui_RollPanel = lv_obj_create(ui_ButtonContainer);
    lv_obj_set_width(ui_RollPanel, 90);
    lv_obj_set_height(ui_RollPanel, 55);
    lv_obj_set_x(ui_RollPanel, 0);
    lv_obj_set_y(ui_RollPanel, -65);
    lv_obj_set_align(ui_RollPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RollPanel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_RollPanel, lv_color_hex(0x968BE4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollLabel = lv_label_create(ui_RollPanel);
    lv_obj_set_width(ui_RollLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_RollLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_RollLabel, -2);
    lv_obj_set_y(ui_RollLabel, -15);
    lv_obj_set_align(ui_RollLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RollLabel, "Roll");

    ui_RollSwitch = lv_obj_create(ui_RollPanel);
    lv_obj_set_width(ui_RollSwitch, 25);
    lv_obj_set_height(ui_RollSwitch, 25);
    lv_obj_set_x(ui_RollSwitch, 0);
    lv_obj_set_y(ui_RollSwitch, 8);
    lv_obj_set_align(ui_RollSwitch, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RollSwitch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_RollSwitch, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollSwitch, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollSwitch, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_RollSwitch, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    // Status Container
    ui_StatusContainer = lv_obj_create(ui_GestureDetectScreen);
    lv_obj_remove_style_all(ui_StatusContainer);
    lv_obj_set_width(ui_StatusContainer, 200);
    lv_obj_set_height(ui_StatusContainer, 50);
    lv_obj_set_x(ui_StatusContainer, 50);
    lv_obj_set_y(ui_StatusContainer, -85);
    lv_obj_set_align(ui_StatusContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_StatusContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_StatusContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatusContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Motion Status Panel
    ui_PickupPanel = lv_obj_create(ui_StatusContainer);
    lv_obj_set_width(ui_PickupPanel, 100);
    lv_obj_set_height(ui_PickupPanel, 40);
    lv_obj_set_x(ui_PickupPanel, 0);
    lv_obj_set_y(ui_PickupPanel, 0);
    lv_obj_set_align(ui_PickupPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PickupPanel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_PickupPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PickupPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PickupStatusLight = lv_obj_create(ui_PickupPanel);
    lv_obj_set_width(ui_PickupStatusLight, 12);
    lv_obj_set_height(ui_PickupStatusLight, 12);
    lv_obj_set_x(ui_PickupStatusLight, -40);
    lv_obj_set_y(ui_PickupStatusLight, 0);
    lv_obj_set_align(ui_PickupStatusLight, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PickupStatusLight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_PickupStatusLight, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PickupStatusLight, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PickupStatusLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PickupStatusLight, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PickupStatusLight, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PickupLabel = lv_label_create(ui_PickupPanel);
    lv_obj_set_width(ui_PickupLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_PickupLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_PickupLabel, 10);
    lv_obj_set_y(ui_PickupLabel, 0);
    lv_obj_set_align(ui_PickupLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PickupLabel, "no motion");
    lv_obj_set_style_text_align(ui_PickupLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Put down Status Panel
    ui_PutdownPanel = lv_obj_create(ui_StatusContainer);
    lv_obj_set_width(ui_PutdownPanel, 60);
    lv_obj_set_height(ui_PutdownPanel, 40);
    lv_obj_set_x(ui_PutdownPanel, 40);
    lv_obj_set_y(ui_PutdownPanel, 0);
    lv_obj_set_align(ui_PutdownPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PutdownPanel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_PutdownPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PutdownPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_PutdownPanel, LV_OBJ_FLAG_HIDDEN);

    ui_PutdownStatusLight = lv_obj_create(ui_PutdownPanel);
    lv_obj_set_width(ui_PutdownStatusLight, 12);
    lv_obj_set_height(ui_PutdownStatusLight, 12);
    lv_obj_set_x(ui_PutdownStatusLight, -15);
    lv_obj_set_y(ui_PutdownStatusLight, 0);
    lv_obj_set_align(ui_PutdownStatusLight, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PutdownStatusLight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_PutdownStatusLight, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PutdownStatusLight, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PutdownStatusLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PutdownStatusLight, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PutdownStatusLight, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_add_flag(ui_PutdownStatusLight, LV_OBJ_FLAG_HIDDEN);

    ui_PutdownLabel = lv_label_create(ui_PutdownPanel);
    lv_obj_set_width(ui_PutdownLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_PutdownLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_PutdownLabel, 0);
    lv_obj_set_y(ui_PutdownLabel, 0);
    lv_obj_set_align(ui_PutdownLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PutdownLabel, "no motion");

    // Gesture Detail Label
    ui_GestureDetailLabel = lv_label_create(ui_GestureDetectScreen);
    lv_obj_set_width(ui_GestureDetailLabel, 150);
    lv_obj_set_height(ui_GestureDetailLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_GestureDetailLabel, 50);
    lv_obj_set_y(ui_GestureDetailLabel, -60);
    lv_obj_set_align(ui_GestureDetailLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GestureDetailLabel, "");
    lv_label_set_long_mode(ui_GestureDetailLabel, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_align(ui_GestureDetailLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_GestureDetailLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_GestureDetailLabel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_flag(ui_GestureDetailLabel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // Image Container
    ui_ImageContainer = lv_obj_create(ui_GestureDetectScreen);
    lv_obj_remove_style_all(ui_ImageContainer);
    lv_obj_set_width(ui_ImageContainer, 150);
    lv_obj_set_height(ui_ImageContainer, 150);
    lv_obj_set_x(ui_ImageContainer, 50);
    lv_obj_set_y(ui_ImageContainer, 20);
    lv_obj_set_align(ui_ImageContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ImageContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_move_foreground(ui_ImageContainer);

    ui_SuccessImage = lv_image_create(ui_ImageContainer);
    lv_image_set_src(ui_SuccessImage, &ui_img_success_png);
    lv_obj_set_width(ui_SuccessImage, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_SuccessImage, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_SuccessImage, 30);
    lv_obj_set_y(ui_SuccessImage, 32);
    lv_obj_set_align(ui_SuccessImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SuccessImage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_SuccessImage, LV_OBJ_FLAG_SCROLLABLE);

    // Gesture Image
    ui_GestureImage = lv_image_create(ui_ImageContainer);
    lv_image_set_src(ui_GestureImage, &ui_img_pickup_png);
    lv_obj_set_width(ui_GestureImage, 130);
    lv_obj_set_height(ui_GestureImage, 130);
    lv_obj_set_align(ui_GestureImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GestureImage, LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_flag(ui_GestureImage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // Ready Label
    ui_ReadyLabel = lv_label_create(ui_GestureDetectScreen);
    lv_obj_set_width(ui_ReadyLabel, 130);
    lv_obj_set_height(ui_ReadyLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_ReadyLabel, 50);
    lv_obj_set_y(ui_ReadyLabel, -10);
    lv_obj_set_align(ui_ReadyLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReadyLabel, "Device no motion\n\nYou can:\n- Roll\n (>90°)\n- Shake");
    lv_label_set_long_mode(ui_ReadyLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_align(ui_ReadyLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ReadyLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_ReadyLabel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_flag(ui_ReadyLabel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_move_foreground(ui_ReadyLabel);

    // Motion Detected Label
    ui_MotionDetectedLabel = lv_label_create(ui_GestureDetectScreen);
    lv_obj_set_width(ui_MotionDetectedLabel, 130);
    lv_obj_set_height(ui_MotionDetectedLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_MotionDetectedLabel, 50);
    lv_obj_set_y(ui_MotionDetectedLabel, -10);
    lv_obj_set_align(ui_MotionDetectedLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotionDetectedLabel, "Device is moving\n\nYou can:\n- Roll\n (>90°)\n- Shake");
    lv_label_set_long_mode(ui_MotionDetectedLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_align(ui_MotionDetectedLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_MotionDetectedLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_MotionDetectedLabel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_remove_flag(ui_MotionDetectedLabel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_move_foreground(ui_MotionDetectedLabel);

    update_gesture_ui(GESTURE_PICKUP);

}

void ui_GestureDetectScreen_screen_destroy(void)
{
    if (ui_GestureDetectScreen) {
        lv_obj_del(ui_GestureDetectScreen);
    }

    ui_GestureDetectScreen = NULL;
    ui_ButtonContainer = NULL;
    ui_ShakePanel = NULL;
    ui_ShakeLabel = NULL;
    ui_ShakeSwitch = NULL;
    ui_RollPanel = NULL;
    ui_RollLabel = NULL;
    ui_RollSwitch = NULL;
    ui_AxisContainer = NULL;
    ui_AxisXLine = NULL;
    ui_AxisYLine = NULL;
    ui_AxisZLine = NULL;
    ui_AxisXArrow1 = NULL;
    ui_AxisXArrow2 = NULL;
    ui_AxisYArrow1 = NULL;
    ui_AxisYArrow2 = NULL;
    ui_AxisZArrow1 = NULL;
    ui_AxisZArrow2 = NULL;
    ui_AxisXLabel = NULL;
    ui_AxisYLabel = NULL;
    ui_AxisZLabel = NULL;
    ui_StatusContainer = NULL;
    ui_PickupPanel = NULL;
    ui_PickupStatusLight = NULL;
    ui_PickupLabel = NULL;
    ui_PutdownPanel = NULL;
    ui_PutdownStatusLight = NULL;
    ui_PutdownLabel = NULL;
    ui_ImageContainer = NULL;
    ui_SuccessImage = NULL;
    ui_GestureImage = NULL;
    ui_ReadyLabel = NULL;
    ui_MotionDetectedLabel = NULL;
    ui_GestureDetailLabel = NULL;

}
