/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Gesture

#include "../ui.h"

lv_obj_t *ui_GestureDetectTipScreen = NULL;
lv_obj_t *ui_Label1 = NULL;
// event functions

// build functions

void ui_GestureDetectTipScreen_screen_init(void)
{
    ui_GestureDetectTipScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_GestureDetectTipScreen, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_GestureDetectTipScreen, lv_color_hex(0xDCC7E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GestureDetectTipScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_GestureDetectTipScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "BMI270 sub-board not detected.\nPower off and insert sub-board.\nDo NOT hot-plug.");
    lv_label_set_long_mode(ui_Label1, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_GestureDetectTipScreen_screen_destroy(void)
{
    if (ui_GestureDetectTipScreen) {
        lv_obj_del(ui_GestureDetectTipScreen);
    }

    ui_GestureDetectTipScreen = NULL;
    ui_Label1 = NULL;

}
