// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: UI_Setting

#include "ui.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenSettingMain
void ui_ScreenSettingMain_screen_init(void);
lv_obj_t *ui_ScreenSettingMain;
lv_obj_t *ui_PanelSettingMainContainer;
void ui_event_PanelSettingMainContainerItem1( lv_event_t * e);
lv_obj_t *ui_PanelSettingMainContainerItem1;
lv_obj_t *ui_ImagePanelSettingMainContainer1WiFi;
lv_obj_t *ui_ImagePanelSettingMainContainer1Arrow;
lv_obj_t *ui_LabelPanelSettingMainContainer1WiFi;
void ui_event_PanelSettingMainContainerItem2( lv_event_t * e);
lv_obj_t *ui_PanelSettingMainContainerItem2;
lv_obj_t *ui_ImagePanelSettingMainContainer2Blue;
lv_obj_t *ui_ImagePanelSettingMainContainer2Arrow;
lv_obj_t *ui_LabelPanelSettingMainContainer2Blue;
void ui_event_PanelSettingMainContainerItem3( lv_event_t * e);
lv_obj_t *ui_PanelSettingMainContainerItem3;
lv_obj_t *ui_ImagePanelSettingMainContainer3Volume;
lv_obj_t *ui_ImagePanelSettingMainContainer3Arrow;
lv_obj_t *ui_LabelPanelSettingMainContainer3Volume;
void ui_event_PanelSettingMainContainerItem4( lv_event_t * e);
lv_obj_t *ui_PanelSettingMainContainerItem4;
lv_obj_t *ui_ImagePanelSettingMainContainer4Light;
lv_obj_t *ui_ImagePanelSettingMainContainer4Arrow;
lv_obj_t *ui_LabelPanelSettingMainContainer4Light;
void ui_event_PanelSettingMainContainerItem5( lv_event_t * e);
lv_obj_t *ui_PanelSettingMainContainerItem5;
lv_obj_t *ui_ImagePanelSettingMainContainer5About;
lv_obj_t *ui_ImagePanelSettingMainContainer5Arrow;
lv_obj_t *ui_LabelPanelSettingMainContainer5About;


// SCREEN: ui_ScreenSettingWiFi
void ui_ScreenSettingWiFi_screen_init(void);
lv_obj_t *ui_ScreenSettingWiFi;
lv_obj_t *ui_PanelScreenSettingWiFiSwitch;
lv_obj_t *ui_ImagePanelScreenSettingWiFiSwitch;
lv_obj_t *ui_LabelPanelScreenSettingWiFiSwitch;
lv_obj_t *ui_SwitchPanelScreenSettingWiFiSwitch;
lv_obj_t *ui_PanelScreenSettingWiFiList;
lv_obj_t *ui_SpinnerScreenSettingWiFi;
void ui_event_ButtonScreenSettingWiFiReturn( lv_event_t * e);
lv_obj_t *ui_ButtonScreenSettingWiFiReturn;
lv_obj_t *ui_ImageScreenSettingWiFiReturn;


// SCREEN: ui_ScreenSettingBLE
void ui_ScreenSettingBLE_screen_init(void);
lv_obj_t *ui_ScreenSettingBLE;
lv_obj_t *ui_PanelScreenSettingBLESwitch;
lv_obj_t *ui_ImagePanelScreenSettingBLESwitch;
lv_obj_t *ui_LabelPanelScreenSettingBLESwitch;
lv_obj_t *ui_SwitchPanelScreenSettingBLESwitch;
lv_obj_t *ui_PanelScreenSettingBLEList;
lv_obj_t *ui_SpinnerScreenSettingBLE;
void ui_event_ButtonScreenSettingBLEReturn( lv_event_t * e);
lv_obj_t *ui_ButtonScreenSettingBLEReturn;
lv_obj_t *ui_ImageScreenSettingBLEReturn;


// SCREEN: ui_ScreenSettingVolume
void ui_ScreenSettingVolume_screen_init(void);
lv_obj_t *ui_ScreenSettingVolume;
lv_obj_t *ui_PanelScreenSettingVolumeSwitch;
lv_obj_t *ui_ImagePanelScreenSettingVolumeSwitch;
lv_obj_t *ui_LabelPanelScreenSettingVolumeSwitch;
lv_obj_t *ui_SliderPanelScreenSettingVolumeSwitch;
lv_obj_t *ui_PanelScreenSettingVolumeList;
lv_obj_t *ui_SpinnerScreenSettingVolume;
void ui_event_ButtonScreenSettingVolumeReturn( lv_event_t * e);
lv_obj_t *ui_ButtonScreenSettingVolumeReturn;
lv_obj_t *ui_ImageScreenSettingVolumeReturn;


// SCREEN: ui_ScreenSettingLight
void ui_ScreenSettingLight_screen_init(void);
lv_obj_t *ui_ScreenSettingLight;
lv_obj_t *ui_PanelScreenSettingLightSwitch;
lv_obj_t *ui_ImagePanelScreenSettingLightSwitch;
lv_obj_t *ui_LabelPanelScreenSettingLightSwitch;
lv_obj_t *ui_SliderPanelScreenSettingLightSwitch1;
lv_obj_t *ui_PanelScreenSettingLightList;
lv_obj_t *ui_SpinnerScreenSettingLight;
void ui_event_ButtonScreenSettingLightReturn( lv_event_t * e);
lv_obj_t *ui_ButtonScreenSettingLightReturn;
lv_obj_t *ui_ImageScreenSettingLightReturn;


// SCREEN: ui_ScreenSettingAbout
void ui_ScreenSettingAbout_screen_init(void);
lv_obj_t *ui_ScreenSettingAbout;
lv_obj_t *ui_PanelScreenSettingAboutList;
lv_obj_t *ui_SpinnerScreenAboutList;
void ui_event_ButtonScreenSettingAboutReturn( lv_event_t * e);
lv_obj_t *ui_ButtonScreenSettingAboutReturn;
lv_obj_t *ui_ImageScreenSettingAboutReturn;
lv_obj_t *ui_ImageScreenSettingAbout;
lv_obj_t *ui_PanelScreenSettingAbout;
lv_obj_t *ui_PanelPanelScreenSettingAbout;
lv_obj_t *ui_LabelPanelPanelScreenSettingAboutDevice;
lv_obj_t *ui_LabelPanelPanelScreenSettingAbout2;
lv_obj_t *ui_PanelPanelScreenSettingAbout1;
lv_obj_t *ui_LabelPanelPanelScreenSettingAboutManufacturer;
lv_obj_t *ui_LabelPanelPanelScreenSettingAbout1;
lv_obj_t *ui_PanelPanelScreenSettingAbout2;
lv_obj_t *ui_LabelPanelPanelScreenSettingAboutMAC;
lv_obj_t *ui_LabelPanelPanelScreenSettingAbout3;
lv_obj_t *ui_PanelPanelScreenSettingAbout3;
lv_obj_t *ui_LabelPanelPanelScreenSettingAboutUIFramework;
lv_obj_t *ui_LabelPanelPanelScreenSettingAbout4;
lv_obj_t *ui_PanelPanelScreenSettingAbout4;
lv_obj_t *ui_LabelPanelPanelScreenSettingAboutSoftwareVersion;
lv_obj_t *ui_LabelPanelPanelScreenSettingAbout5;
lv_obj_t *ui_PanelPanelScreenSettingAbout5;
lv_obj_t *ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion;
lv_obj_t *ui_LabelPanelPanelScreenSettingAbout6;
lv_obj_t *ui____initial_setting_actions0;

// SCREEN: ui_ScreenSettingVerification
void ui_ScreenSettingVerification_screen_init(void);
lv_obj_t * ui_ScreenSettingVerification;
lv_obj_t * ui_LabelScreenSettingVerification;
lv_obj_t * ui_LabelScreenSettingVerificationSSID;
lv_obj_t * ui_TextAreaScreenSettingVerificationPassword;
void ui_event_KeyboardScreenSettingVerification(lv_event_t * e);
lv_obj_t * ui_KeyboardScreenSettingVerification;
lv_obj_t * ui_SpinnerScreenSettingVerification;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_PanelSettingMainContainerItem1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettingWiFi, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettingWiFi_screen_init);
}
}
void ui_event_PanelSettingMainContainerItem2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettingBLE, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettingBLE_screen_init);
}
}
void ui_event_PanelSettingMainContainerItem3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettingVolume, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettingVolume_screen_init);
}
}
void ui_event_PanelSettingMainContainerItem4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettingLight, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettingLight_screen_init);
}
}
void ui_event_PanelSettingMainContainerItem5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettingAbout, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettingAbout_screen_init);
}
}
void ui_event_ButtonScreenSettingWiFiReturn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettingMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettingMain_screen_init);
}
}
void ui_event_ButtonScreenSettingBLEReturn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettingMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettingMain_screen_init);
}
}
void ui_event_ButtonScreenSettingVolumeReturn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettingMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettingMain_screen_init);
}
}
void ui_event_ButtonScreenSettingLightReturn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettingMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettingMain_screen_init);
}
}
void ui_event_ButtonScreenSettingAboutReturn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSettingMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSettingMain_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_setting_init( void )
{
ui_ScreenSettingMain_screen_init();
ui_ScreenSettingWiFi_screen_init();
ui_ScreenSettingBLE_screen_init();
ui_ScreenSettingVolume_screen_init();
ui_ScreenSettingLight_screen_init();
ui_ScreenSettingAbout_screen_init();
ui_ScreenSettingVerification_screen_init();
ui____initial_setting_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ScreenSettingMain);
}
