# Note: All operators are binary operators. For more than two operands, you may use the nested parentheses trick.
# For example:
#    *  A == 1 or (B == 2 and C in [1,2,3])
#    *  (A == 1 and B == 2) or (C not in ["3", "4", 5])

esp32-c3-lcdkit:
  enable:
    - if: IDF_TARGET == "esp32c3"

esp32-s2-hmi-devkit-1:
  enable:
    - if: IDF_TARGET == "esp32s2"

esp32-s2-kaluga-1:
  enable:
    - if: IDF_TARGET == "esp32s2"

esp32-s2-touch-devkit-1:
  enable:
    - if: IDF_TARGET == "esp32s2"

esp32-s3-lcd-ev-board:
  enable:
    - if: IDF_TARGET == "esp32s3"

esp32-s3-usb-bridge:
  enable:
    - if: IDF_TARGET == "esp32s3"

esp32-s3-usb-otg:
  enable:
    - if: IDF_TARGET == "esp32s3"
