/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Temp

#ifndef UI_TemperatureSCREEN_H
#define UI_TemperatureSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TemperatureScreen
extern void ui_TemperatureScreen_screen_init(void);
extern void ui_TemperatureScreen_screen_destroy(void);
extern lv_obj_t *ui_TemperatureScreen;
extern lv_obj_t *ui_TimeLabel;
extern lv_obj_t *ui_BatteryLabel;
extern lv_obj_t *ui_Temperature;
extern lv_obj_t *ui_TemperatureLabel;
extern lv_obj_t *ui_TemperatureNumber;
extern lv_obj_t *ui_TemperatureSignal;
extern lv_obj_t *ui_TemperatureStatus;
extern lv_obj_t *ui_Thermometer;
extern lv_obj_t *ui_Fire;
extern lv_obj_t *ui_Humidity;
extern lv_obj_t *ui_HumidityLabel;
extern lv_obj_t *ui_Water;
extern lv_obj_t *ui_HumidityNumber;
extern lv_obj_t *ui_HumidityUnit;
extern lv_obj_t *ui_HumidityEvaluation;
extern lv_obj_t *ui_Pressure;
extern lv_obj_t *ui_PressureLabel;
extern lv_obj_t *ui_PressureImage;
extern lv_obj_t *ui_PressureText;
extern lv_obj_t *ui_PressureUnit;
extern lv_obj_t *ui_PressureTrend;
extern lv_obj_t *ui_AirQuality;
extern lv_obj_t *ui_AirQualityLabel;
extern lv_obj_t *ui_Leaf;
extern lv_obj_t *ui_AirQualityCO2;
extern lv_obj_t *ui_AirQualityNumber;
extern lv_obj_t *ui_AirQualityLevel;
extern lv_obj_t *ui_AirQualitySignal;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
