// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: image_display

#include "ui.h"
#include "app_ui_control.h"

void leftReviewCB(lv_event_t * e)
{
	// Your code here
	ui_control_up_display();
}

void rightReviewCB(lv_event_t * e)
{
	// Your code here
	ui_control_down_display();
}

void displayObj_clicked_cb(lv_event_t * e)
{
	// Your code here
	if (lv_obj_has_flag(ui_leftBtn, LV_OBJ_FLAG_HIDDEN)) {
		lv_obj_clear_flag(ui_leftBtn, LV_OBJ_FLAG_HIDDEN);
		lv_obj_clear_flag(ui_rightBtn, LV_OBJ_FLAG_HIDDEN);
		lv_obj_clear_flag(ui_Label1, LV_OBJ_FLAG_HIDDEN);
		lv_obj_clear_flag(ui_Label2, LV_OBJ_FLAG_HIDDEN);
		lv_obj_clear_flag(ui_Label4, LV_OBJ_FLAG_HIDDEN);
		lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_HIDDEN);
		lv_obj_clear_flag(ui_Filename, LV_OBJ_FLAG_HIDDEN);
	} else {
		lv_obj_add_flag(ui_leftBtn, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_rightBtn, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_Label1, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_Label2, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_Label4, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_Filename, LV_OBJ_FLAG_HIDDEN);
	}
}
