/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Gesture

#include "ui.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void gesture_detect_ui_init(bool is_initialized)
{
    lv_disp_t *dispp = lv_display_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_GestureDetectTipScreen_screen_init();
    ui_GestureDetectScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    if (is_initialized) {
        lv_disp_load_scr(ui_GestureDetectScreen);
    } else {
        lv_disp_load_scr(ui_GestureDetectTipScreen);
    }
}

void gesture_detect_ui_destroy(void)
{
    ui_GestureDetectTipScreen_screen_destroy();
    ui_GestureDetectScreen_screen_destroy();
}
