/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Gesture

#ifndef _GESTURE_UI_H
#define _GESTURE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_GestureDetectTipScreen.h"
#include "screens/ui_GestureDetectScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS

extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_pickup_png);    // assets/Pickup.png
LV_IMG_DECLARE(ui_img_throw_png);    // assets/Throw.png
LV_IMG_DECLARE(ui_img_shake_png);    // assets/Shake.png
LV_IMG_DECLARE(ui_img_success_png);    // assets/Success.png

// UI INIT
void gesture_detect_ui_init(bool is_initialized);
void gesture_detect_ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
