/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Gesture

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ui.h"
#include "ui_app.h"

void PickupSwitchChecked(lv_event_t *e);
void PickupSwitchUnchecked(lv_event_t *e);
void PutdownSwitchChecked(lv_event_t *e);
void PutdownSwitchUnchecked(lv_event_t *e);
void ShakeSwitchChecked(lv_event_t *e);
void ShakeSwitchUnchecked(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
