/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Gesture

#include "ui.h"
#include "ui_app.h"

void PickupSwitchChecked(lv_event_t *e)
{
    set_current_gesture(GESTURE_PICKUP);
    lv_obj_clear_state(ui_ShakeSwitch, LV_STATE_CHECKED);
    lv_obj_add_state(ui_PickupStatusLight, LV_STATE_CHECKED);
    lv_obj_clear_state(ui_PutdownStatusLight, LV_STATE_CHECKED);
}

void PickupSwitchUnchecked(lv_event_t *e)
{
    lv_obj_add_state(ui_PickupStatusLight, LV_STATE_CHECKED);
}

void PutdownSwitchChecked(lv_event_t *e)
{
    set_current_gesture(GESTURE_PUTDOWN);
    lv_obj_clear_state(ui_ShakeSwitch, LV_STATE_CHECKED);
    lv_obj_add_state(ui_PutdownStatusLight, LV_STATE_CHECKED);
    lv_obj_clear_state(ui_PickupStatusLight, LV_STATE_CHECKED);
}

void PutdownSwitchUnchecked(lv_event_t *e)
{
    lv_obj_add_state(ui_PutdownStatusLight, LV_STATE_CHECKED);
}

void ShakeSwitchChecked(lv_event_t *e)
{
    set_current_gesture(GESTURE_SHAKE);
    lv_obj_clear_state(ui_PickupStatusLight, LV_STATE_CHECKED);
    lv_obj_clear_state(ui_PutdownStatusLight, LV_STATE_CHECKED);
    lv_obj_set_style_bg_image_src(ui_ImageContainer, &ui_img_shake_png, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ShakeSwitchUnchecked(lv_event_t *e)
{
    lv_obj_add_state(ui_ShakeSwitch, LV_STATE_CHECKED);
}
