// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: image_display

#include <stdio.h>
#include "../ui.h"

void ui_displayPage_screen_init(void)
{
    ui_displayPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_displayPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_leftBtn = lv_img_create(ui_displayPage);
    lv_img_set_src(ui_leftBtn, &ui_img_arrow_png);
    lv_obj_set_width(ui_leftBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_leftBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_leftBtn, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_leftBtn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_leftBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_leftBtn, 0);

    ui_rightBtn = lv_img_create(ui_displayPage);
    lv_img_set_src(ui_rightBtn, &ui_img_arrow_png);
    lv_obj_set_width(ui_rightBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rightBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rightBtn, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_rightBtn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rightBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_rightBtn, 1800);

    ui_Filename = lv_label_create(ui_displayPage);
    lv_obj_set_width(ui_Filename, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Filename, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Filename, 0);
    lv_obj_set_y(ui_Filename, -200);
    lv_obj_set_align(ui_Filename, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Filename, "");
    lv_obj_set_style_text_font(ui_Filename, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_displayPage);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -30);
    lv_obj_set_y(ui_Label2, 200);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "1");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_displayPage);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 30);
    lv_obj_set_y(ui_Label1, 200);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "10");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_displayPage);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 200);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "/");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_displayPage);
    lv_img_set_src(ui_Image3, &ui_img_return_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_leftBtn, ui_event_leftBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rightBtn, ui_event_rightBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image3, ui_event_Image3, LV_EVENT_ALL, NULL);
}

void ui_displayObj_clear(void)
{
    if (ui_displayObj != NULL) {
        lv_obj_del_async(ui_displayObj);
        ui_displayObj = NULL;
    }
}

void ui_displayObj_hidden(void)
{
    if (ui_displayObj != NULL) {
        lv_obj_add_flag(ui_displayObj, LV_OBJ_FLAG_HIDDEN);
        ui_displayObj = NULL;
    }
}

bool ui_displayPage_create_dispalyObj(ui_file_type_t type)
{
    ui_displayObj_clear();

    switch (type)
    {
    case UI_FILE_TYPE_JPG:
    case UI_FILE_TYPE_PNG:
    case UI_FILE_TYPE_BMP:
        ui_displayObj = lv_img_create(ui_displayPage);
        break;
    case UI_FILE_TYPE_GIF:
    case UI_FILE_TYPE_MP3:
        ui_displayObj = lv_gif_create(ui_displayPage);
        break;
    default:
        printf("ui_displayObj create failed\n");
        return false;
    }

    lv_obj_set_width(ui_displayObj, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_displayObj, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_displayObj, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_displayObj, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_displayObj, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_displayObj, ui_event_displayObj, LV_EVENT_ALL, NULL);
    lv_obj_move_background(ui_displayObj);
    return true;
}