// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: image_display

#include "../ui.h"

void ui_StartPage_screen_init(void)
{
    ui_StartPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StartPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imageMSC = lv_img_create(ui_StartPage);
    lv_img_set_src(ui_imageMSC, &ui_img_pullmscbig_png);
    lv_obj_set_width(ui_imageMSC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imageMSC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imageMSC, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imageMSC, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imageMSC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_startLable = lv_label_create(ui_StartPage);
    lv_obj_set_width(ui_startLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_startLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_startLable, 0);
    lv_obj_set_y(ui_startLable, 85);
    lv_obj_set_align(ui_startLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_startLable, "Please insert a USB stick");
    lv_obj_set_style_text_font(ui_startLable, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_imageMSC, ui_event_imageMSC, LV_EVENT_ALL, NULL);

}