// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Camera

#include "../ui.h"

void ui_ScreenCameraPhoto_screen_init(void)
{
ui_ScreenCameraPhoto = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenCameraPhoto, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_ScreenCameraPhoto,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ScreenCameraPhoto, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_ScreenCameraPhoto, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenCameraPhoto, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_ScreenCameraPhoto, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ScreenCameraPhoto, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ScreenCameraPhoto, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ScreenCameraPhoto, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_ScreenCameraPhoto, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_ScreenCameraPhoto, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelCameraPhotoTitle = lv_obj_create(ui_ScreenCameraPhoto);
lv_obj_set_height( ui_PanelCameraPhotoTitle, 80);
lv_obj_set_width( ui_PanelCameraPhotoTitle, lv_pct(100));
lv_obj_set_align( ui_PanelCameraPhotoTitle, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_PanelCameraPhotoTitle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelCameraPhotoTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelCameraPhotoTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelCameraPhotoTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PanelCameraPhotoTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelCameraPhotoTitle = lv_label_create(ui_PanelCameraPhotoTitle);
lv_obj_set_width( ui_LabelCameraPhotoTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelCameraPhotoTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelCameraPhotoTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelCameraPhotoTitle,"Photo");
lv_obj_set_style_text_color(ui_LabelCameraPhotoTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelCameraPhotoTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelCameraPhotoTitle, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageCameraPhotoImage = lv_img_create(ui_ScreenCameraPhoto);
lv_obj_set_height( ui_ImageCameraPhotoImage, 432);
lv_obj_set_width( ui_ImageCameraPhotoImage, lv_pct(100));
lv_obj_set_align( ui_ImageCameraPhotoImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageCameraPhotoImage, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_EVENT_BUBBLE );   /// Flags
lv_obj_clear_flag( ui_ImageCameraPhotoImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_ScreenCameraPhoto, ui_event_ScreenCameraPhoto, LV_EVENT_ALL, NULL);

}
