/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Temp

#ifndef _TEMP_UI_H
#define _TEMP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_TemperatureScreen.h"
#include "screens/ui_TemperatureTipScreen.h"

// UI INIT
void Temperature_ui_init(bool is_initialized);
void Temperature_ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
