// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: UI_Setting

#include "../ui.h"

void ui_ScreenSettingMain_screen_init(void)
{
ui_ScreenSettingMain = lv_obj_create(NULL);
lv_obj_set_style_bg_color(ui_ScreenSettingMain, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenSettingMain, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelSettingMainContainer = lv_obj_create(ui_ScreenSettingMain);
lv_obj_set_width( ui_PanelSettingMainContainer, 720);
lv_obj_set_height( ui_PanelSettingMainContainer, 428);
lv_obj_set_x( ui_PanelSettingMainContainer, 150 );
lv_obj_set_y( ui_PanelSettingMainContainer, 98 );
lv_obj_set_flex_flow(ui_PanelSettingMainContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanelSettingMainContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanelSettingMainContainer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_PanelSettingMainContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelSettingMainContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelSettingMainContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelSettingMainContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelSettingMainContainerItem1 = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_height( ui_PanelSettingMainContainerItem1, 70);
lv_obj_set_width( ui_PanelSettingMainContainerItem1, lv_pct(100));
lv_obj_set_y( ui_PanelSettingMainContainerItem1, -230 );
lv_obj_set_x( ui_PanelSettingMainContainerItem1, lv_pct(1) );
lv_obj_set_align( ui_PanelSettingMainContainerItem1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSettingMainContainerItem1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelSettingMainContainerItem1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelSettingMainContainerItem1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem1, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem1, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ImagePanelSettingMainContainer1WiFi = lv_img_create(ui_PanelSettingMainContainerItem1);
lv_img_set_src(ui_ImagePanelSettingMainContainer1WiFi, &ui_img_wifi_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer1WiFi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer1WiFi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer1WiFi, 2 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer1WiFi, lv_pct(-48) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer1WiFi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer1WiFi, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer1WiFi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelSettingMainContainer1Arrow = lv_img_create(ui_PanelSettingMainContainerItem1);
lv_img_set_src(ui_ImagePanelSettingMainContainer1Arrow, &ui_img_arrow_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer1Arrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer1Arrow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer1Arrow, 0 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer1Arrow, lv_pct(49) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer1Arrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer1Arrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer1Arrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelSettingMainContainer1WiFi = lv_label_create(ui_PanelSettingMainContainerItem1);
lv_obj_set_width( ui_LabelPanelSettingMainContainer1WiFi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelSettingMainContainer1WiFi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelSettingMainContainer1WiFi, -240 );
lv_obj_set_y( ui_LabelPanelSettingMainContainer1WiFi, 2 );
lv_obj_set_align( ui_LabelPanelSettingMainContainer1WiFi, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelSettingMainContainer1WiFi,"Wi-Fi");
lv_obj_set_style_text_font(ui_LabelPanelSettingMainContainer1WiFi, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelSettingMainContainerItem2 = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_width( ui_PanelSettingMainContainerItem2, 719);
lv_obj_set_height( ui_PanelSettingMainContainerItem2, 70);
lv_obj_set_x( ui_PanelSettingMainContainerItem2, 7 );
lv_obj_set_y( ui_PanelSettingMainContainerItem2, -130 );
lv_obj_set_align( ui_PanelSettingMainContainerItem2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSettingMainContainerItem2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelSettingMainContainerItem2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelSettingMainContainerItem2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem2, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem2, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ImagePanelSettingMainContainer2Blue = lv_img_create(ui_PanelSettingMainContainerItem2);
lv_img_set_src(ui_ImagePanelSettingMainContainer2Blue, &ui_img_bluetooth_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer2Blue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer2Blue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer2Blue, 2 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer2Blue, lv_pct(-48) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer2Blue, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer2Blue, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer2Blue, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelSettingMainContainer2Arrow = lv_img_create(ui_PanelSettingMainContainerItem2);
lv_img_set_src(ui_ImagePanelSettingMainContainer2Arrow, &ui_img_arrow_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer2Arrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer2Arrow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer2Arrow, 0 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer2Arrow, lv_pct(49) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer2Arrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer2Arrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer2Arrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelSettingMainContainer2Blue = lv_label_create(ui_PanelSettingMainContainerItem2);
lv_obj_set_width( ui_LabelPanelSettingMainContainer2Blue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelSettingMainContainer2Blue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelSettingMainContainer2Blue, -206 );
lv_obj_set_y( ui_LabelPanelSettingMainContainer2Blue, 2 );
lv_obj_set_align( ui_LabelPanelSettingMainContainer2Blue, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelSettingMainContainer2Blue,"Bluetooth");
lv_obj_set_style_text_font(ui_LabelPanelSettingMainContainer2Blue, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelSettingMainContainerItem3 = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_width( ui_PanelSettingMainContainerItem3, 719);
lv_obj_set_height( ui_PanelSettingMainContainerItem3, 70);
lv_obj_set_x( ui_PanelSettingMainContainerItem3, 9 );
lv_obj_set_y( ui_PanelSettingMainContainerItem3, -30 );
lv_obj_set_align( ui_PanelSettingMainContainerItem3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSettingMainContainerItem3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelSettingMainContainerItem3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelSettingMainContainerItem3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem3, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem3, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ImagePanelSettingMainContainer3Volume = lv_img_create(ui_PanelSettingMainContainerItem3);
lv_img_set_src(ui_ImagePanelSettingMainContainer3Volume, &ui_img_sound_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer3Volume, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer3Volume, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer3Volume, 2 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer3Volume, lv_pct(-48) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer3Volume, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer3Volume, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer3Volume, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelSettingMainContainer3Arrow = lv_img_create(ui_PanelSettingMainContainerItem3);
lv_img_set_src(ui_ImagePanelSettingMainContainer3Arrow, &ui_img_arrow_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer3Arrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer3Arrow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer3Arrow, 0 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer3Arrow, lv_pct(49) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer3Arrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer3Arrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer3Arrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelSettingMainContainer3Volume = lv_label_create(ui_PanelSettingMainContainerItem3);
lv_obj_set_width( ui_LabelPanelSettingMainContainer3Volume, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelSettingMainContainer3Volume, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelSettingMainContainer3Volume, -221 );
lv_obj_set_y( ui_LabelPanelSettingMainContainer3Volume, 1 );
lv_obj_set_align( ui_LabelPanelSettingMainContainer3Volume, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelSettingMainContainer3Volume,"Volume");
lv_obj_set_style_text_font(ui_LabelPanelSettingMainContainer3Volume, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelSettingMainContainerItem4 = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_width( ui_PanelSettingMainContainerItem4, 719);
lv_obj_set_height( ui_PanelSettingMainContainerItem4, 70);
lv_obj_set_x( ui_PanelSettingMainContainerItem4, 5 );
lv_obj_set_y( ui_PanelSettingMainContainerItem4, 70 );
lv_obj_set_align( ui_PanelSettingMainContainerItem4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSettingMainContainerItem4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelSettingMainContainerItem4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelSettingMainContainerItem4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem4, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem4, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ImagePanelSettingMainContainer4Light = lv_img_create(ui_PanelSettingMainContainerItem4);
lv_img_set_src(ui_ImagePanelSettingMainContainer4Light, &ui_img_light_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer4Light, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer4Light, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer4Light, 2 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer4Light, lv_pct(-48) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer4Light, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer4Light, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer4Light, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelSettingMainContainer4Arrow = lv_img_create(ui_PanelSettingMainContainerItem4);
lv_img_set_src(ui_ImagePanelSettingMainContainer4Arrow, &ui_img_arrow_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer4Arrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer4Arrow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer4Arrow, 0 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer4Arrow, lv_pct(49) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer4Arrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer4Arrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer4Arrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelSettingMainContainer4Light = lv_label_create(ui_PanelSettingMainContainerItem4);
lv_obj_set_width( ui_LabelPanelSettingMainContainer4Light, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelSettingMainContainer4Light, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelSettingMainContainer4Light, -201 );
lv_obj_set_y( ui_LabelPanelSettingMainContainer4Light, 2 );
lv_obj_set_align( ui_LabelPanelSettingMainContainer4Light, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelSettingMainContainer4Light,"Brightness");
lv_obj_set_style_text_font(ui_LabelPanelSettingMainContainer4Light, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelSettingMainContainerItem5 = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_width( ui_PanelSettingMainContainerItem5, 719);
lv_obj_set_height( ui_PanelSettingMainContainerItem5, 70);
lv_obj_set_x( ui_PanelSettingMainContainerItem5, 3 );
lv_obj_set_y( ui_PanelSettingMainContainerItem5, 170 );
lv_obj_set_align( ui_PanelSettingMainContainerItem5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSettingMainContainerItem5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelSettingMainContainerItem5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelSettingMainContainerItem5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem5, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem5, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem5, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem5, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ImagePanelSettingMainContainer5About = lv_img_create(ui_PanelSettingMainContainerItem5);
lv_img_set_src(ui_ImagePanelSettingMainContainer5About, &ui_img_about_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer5About, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer5About, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer5About, 2 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer5About, lv_pct(-48) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer5About, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer5About, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer5About, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelSettingMainContainer5Arrow = lv_img_create(ui_PanelSettingMainContainerItem5);
lv_img_set_src(ui_ImagePanelSettingMainContainer5Arrow, &ui_img_arrow_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer5Arrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer5Arrow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer5Arrow, 0 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer5Arrow, lv_pct(49) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer5Arrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer5Arrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer5Arrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelSettingMainContainer5About = lv_label_create(ui_PanelSettingMainContainerItem5);
lv_obj_set_width( ui_LabelPanelSettingMainContainer5About, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelSettingMainContainer5About, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelSettingMainContainer5About, -183 );
lv_obj_set_y( ui_LabelPanelSettingMainContainer5About, 1 );
lv_obj_set_align( ui_LabelPanelSettingMainContainer5About, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelSettingMainContainer5About,"About Device");
lv_obj_set_style_text_font(ui_LabelPanelSettingMainContainer5About, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_PanelSettingMainContainerItem1, ui_event_PanelSettingMainContainerItem1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PanelSettingMainContainerItem2, ui_event_PanelSettingMainContainerItem2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PanelSettingMainContainerItem3, ui_event_PanelSettingMainContainerItem3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PanelSettingMainContainerItem4, ui_event_PanelSettingMainContainerItem4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PanelSettingMainContainerItem5, ui_event_PanelSettingMainContainerItem5, LV_EVENT_ALL, NULL);

}
