/*
 * SPDX-FileCopyrightText: 2025-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Compass

#include "../ui.h"
#include "widgets/arc/lv_arc.h"
#include "../../compass_wrapper.hpp"

lv_obj_t *ui_CompassScreen = NULL;
lv_obj_t *ui_Pointer = NULL;
lv_obj_t *ui_ProgressBar = NULL;
lv_obj_t *ui_CalibrationTip = NULL;
// event functions
void ui_event_CompassScreen(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_PRESS_LOST || event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        // A warning or navigation can unload this screen before RELEASED.
        // Cancel the pending recalibration so a later release cannot commit it.
        lv_arc_set_value(ui_ProgressBar, 0);
        lv_obj_add_flag(ui_CalibrationTip, LV_OBJ_FLAG_HIDDEN);
        if (event_code == LV_EVENT_PRESS_LOST) {
            lv_obj_clear_flag(ui_Pointer, LV_OBJ_FLAG_HIDDEN);
        }
        return;
    }
    if (event_code == LV_EVENT_LONG_PRESSED) {
        // Reset progress bar when long press starts (in case of previous incomplete calibration)
        lv_arc_set_value(ui_ProgressBar, 0);
        // Show calibration tip when long press starts
        if (ui_CalibrationTip) {
            lv_obj_clear_flag(ui_CalibrationTip, LV_OBJ_FLAG_HIDDEN);
        }
        // Hide compass pointer when calibrating
        if (ui_Pointer) {
            lv_obj_add_flag(ui_Pointer, LV_OBJ_FLAG_HIDDEN);
        }
    }
    if (event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        int32_t current_val = lv_arc_get_value(ui_ProgressBar);
        // Only update if not already at 100%
        if (current_val < 100) {
            int32_t val = current_val + 5;
            if (val >= 100) {
                val = 100;
                // Hide tip when calibration is complete
                if (ui_CalibrationTip) {
                    lv_obj_add_flag(ui_CalibrationTip, LV_OBJ_FLAG_HIDDEN);
                }
                // Hide compass pointer when calibration completes (will exit screen anyway)
                if (ui_Pointer) {
                    lv_obj_add_flag(ui_Pointer, LV_OBJ_FLAG_HIDDEN);
                }
            }
            lv_arc_set_value(ui_ProgressBar, val);
        }
        // RecorrectStart(e);
    }
    if (event_code == LV_EVENT_RELEASED) {
        if (lv_arc_get_value(ui_ProgressBar) == 100) {
            compass_set_correct(false);
            compass_save_calibration_to_nvs_async();
            compass_back();
        } else {
            lv_arc_set_value(ui_ProgressBar, 0);
            // Hide tip when released before completion
            if (ui_CalibrationTip) {
                lv_obj_add_flag(ui_CalibrationTip, LV_OBJ_FLAG_HIDDEN);
            }
            // Show compass pointer again when calibration is cancelled
            if (ui_Pointer) {
                lv_obj_clear_flag(ui_Pointer, LV_OBJ_FLAG_HIDDEN);
            }
        }
    }
}

// build functions

void ui_CompassScreen_screen_init(void)
{
    ui_CompassScreen = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_CompassScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_remove_flag(ui_CompassScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_CompassScreen, &ui_img_compass_base_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pointer = lv_image_create(ui_CompassScreen);
    lv_image_set_src(ui_Pointer, &ui_img_compass_pointer_png);
    lv_obj_set_width(ui_Pointer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pointer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Pointer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pointer, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Pointer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProgressBar = lv_arc_create(ui_CompassScreen);
    lv_arc_set_range(ui_ProgressBar, 0, 100);
    lv_arc_set_value(ui_ProgressBar, 0);
    lv_arc_set_bg_angles(ui_ProgressBar, 0, 360);
    lv_arc_set_rotation(ui_ProgressBar, 270); // Start from top (12 o'clock position)
    lv_obj_set_size(ui_ProgressBar, 240, 240); // Radius: 120 pixels (increased from 100)
    lv_obj_set_align(ui_ProgressBar, LV_ALIGN_CENTER); // Center of screen
    lv_obj_remove_flag(ui_ProgressBar, LV_OBJ_FLAG_CLICKABLE);

    // Set background arc to transparent
    lv_obj_set_style_arc_opa(ui_ProgressBar, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    // Set indicator arc color to white
    lv_obj_set_style_arc_color(ui_ProgressBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ProgressBar, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT); // Increased width for better visibility
    lv_obj_set_style_arc_opa(ui_ProgressBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Completely remove knob (starting point)
    lv_obj_remove_style(ui_ProgressBar, NULL, LV_PART_KNOB);

    // Create calibration tip label (white text only)
    ui_CalibrationTip = lv_label_create(ui_CompassScreen);
    lv_label_set_text(ui_CalibrationTip, "Recalibrating...");
    lv_obj_set_style_text_color(ui_CalibrationTip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalibrationTip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CalibrationTip, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_width(ui_CalibrationTip, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_CalibrationTip, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_CalibrationTip, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_CalibrationTip, -50); // Position on the arc
    // Hide tip by default
    lv_obj_add_flag(ui_CalibrationTip, LV_OBJ_FLAG_HIDDEN);

    lv_obj_add_event_cb(ui_CompassScreen, ui_event_CompassScreen, LV_EVENT_ALL, NULL);

}

void ui_CompassScreen_screen_destroy(void)
{
    if (ui_CompassScreen) {
        lv_obj_del(ui_CompassScreen);
    }

    ui_CompassScreen = NULL;
    ui_Pointer = NULL;
    ui_ProgressBar = NULL;
    ui_CalibrationTip = NULL;

}
