.. toctree::
    :hidden:
    :caption: {IDF_TARGET_NAME} 系列开发板

    ESP32-S3-DevKitC-1 <esp32-s3-devkitc-1/index>
    ESP32-S3-DevKitM-1 <esp32-s3-devkitm-1/index>
    ESP32-S3-USB-OTG <esp32-s3-usb-otg/index>
    ESP32-S3-LCD-EV-Board <esp32-s3-lcd-ev-board/index>
    ESP32-S3-USB-Bridge <esp32-s3-usb-bridge/index>


============================   ===========================
      **{IDF_TARGET_NAME} 系列开发板**
----------------------------------------------------------
|ESP32-S3-DevKitC-1|_            |ESP32-S3-DevKitM-1|_
----------------------------   ---------------------------
`ESP32-S3-DevKitC-1`_            `ESP32-S3-DevKitM-1`_
----------------------------   ---------------------------
|ESP32-S3-USB-OTG|_            |ESP32-S3-LCD-EV-Board|_
----------------------------   ---------------------------
`ESP32-S3-USB-OTG`_            `ESP32-S3-LCD-EV-Board`_
----------------------------   ---------------------------
|ESP32-S3-USB-Bridge|_
----------------------------   ---------------------------
`ESP32-S3-USB-Bridge`_
============================   ===========================

.. |ESP32-S3-DevKitC-1| image:: ../_static/esp32-s3-devkitc-1/esp32-s3-devkitc-1-v1-isometric.png
.. _ESP32-S3-DevKitC-1: esp32-s3-devkitc-1/index.html

.. |ESP32-S3-DevKitM-1| image:: ../_static/esp32-s3-devkitm-1/esp32-s3-devkitm-1-v1-isometric.png
.. _ESP32-S3-DevKitM-1: esp32-s3-devkitm-1/index.html

.. |ESP32-S3-USB-OTG| image:: ../_static/esp32-s3-usb-otg/pic_product_esp32_s3_otg.png
                        :height: 230px
                        :width: 400px
.. _ESP32-S3-USB-OTG: esp32-s3-usb-otg/index.html

.. |ESP32-S3-LCD-EV-Board| image:: ../_static/esp32-s3-lcd-ev-board/ESP32-S3-LCD-EV-Board_480x480.png
.. _ESP32-S3-LCD-EV-Board: esp32-s3-lcd-ev-board/index.html

.. |ESP32-S3-USB-Bridge| image:: ../_static/esp32-s3-usb-bridge/esp32-s3-usb-bridge.png
.. _ESP32-S3-USB-Bridge: esp32-s3-usb-bridge/index.html
