.. toctree::
    :hidden:
    :caption: {IDF_TARGET_NAME} 系列开发板

    ESP32-C5-DevKitC-1 <esp32-c5-devkitc-1/index>


============================   ===========================
      **{IDF_TARGET_NAME} 系列开发板**
----------------------------------------------------------
|ESP32-C5-DevKitC-1|_
----------------------------   ---------------------------
`ESP32-C5-DevKitC-1`_
============================   ===========================

.. |ESP32-C5-DevKitC-1| image:: ../_static/esp32-c5-devkitc-1/esp32-c5-devkitc-1-isometric_v1.1.png
.. _ESP32-C5-DevKitC-1: esp32-c5-devkitc-1/index.html
