// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp32_p4_eye_factory

#include "../ui.h"

void ui_ScreenUSB_screen_init(void)
{
    ui_ScreenUSB = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenUSB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageScreenUSB = lv_img_create(ui_ScreenUSB);
    lv_img_set_src(ui_ImageScreenUSB, &ui_img_usb_page1_png);
    lv_obj_set_width(ui_ImageScreenUSB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageScreenUSB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageScreenUSB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageScreenUSB, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageScreenUSB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageScreenUSBSuccess = lv_img_create(ui_ScreenUSB);
    lv_img_set_src(ui_ImageScreenUSBSuccess, &ui_img_usb_page2_png);
    lv_obj_set_width(ui_ImageScreenUSBSuccess, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageScreenUSBSuccess, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageScreenUSBSuccess, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageScreenUSBSuccess, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageScreenUSBSuccess, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageScreenUSBWarning = lv_img_create(ui_ScreenUSB);
    lv_img_set_src(ui_ImageScreenUSBWarning, &ui_img_usb_page_warning_png);
    lv_obj_set_width(ui_ImageScreenUSBWarning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageScreenUSBWarning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageScreenUSBWarning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageScreenUSBWarning, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageScreenUSBWarning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageUSBNOSDcard = lv_img_create(ui_ScreenUSB);
    lv_img_set_src(ui_ImageUSBNOSDcard, &ui_img_sdcard_no_png);
    lv_obj_set_width(ui_ImageUSBNOSDcard, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageUSBNOSDcard, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageUSBNOSDcard, -102);
    lv_obj_set_y(ui_ImageUSBNOSDcard, -101);
    lv_obj_set_align(ui_ImageUSBNOSDcard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageUSBNOSDcard, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageUSBNOSDcard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
