// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp32_p4_eye_factory

#include "../ui.h"

void ui_ScreenCamera_screen_init(void)
{
    ui_ScreenCamera = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenCamera, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelCanvas = lv_canvas_create(ui_ScreenCamera);
    lv_obj_set_width(ui_PanelCanvas, 240);
    lv_obj_set_height(ui_PanelCanvas, 240);
    lv_obj_set_align(ui_PanelCanvas, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCanvas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanelCanvas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvas, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageCanvasSelect = lv_img_create(ui_PanelCanvas);
    lv_img_set_src(ui_ImageCanvasSelect, &ui_img_button_select_png);
    lv_obj_set_width(ui_ImageCanvasSelect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCanvasSelect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageCanvasSelect, 100);
    lv_obj_set_y(ui_ImageCanvasSelect, -47);
    lv_obj_set_align(ui_ImageCanvasSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCanvasSelect, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCanvasSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageCanvasUp = lv_img_create(ui_PanelCanvas);
    lv_img_set_src(ui_ImageCanvasUp, &ui_img_up_button_png);
    lv_obj_set_width(ui_ImageCanvasUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCanvasUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageCanvasUp, 100);
    lv_obj_set_y(ui_ImageCanvasUp, 0);
    lv_obj_set_align(ui_ImageCanvasUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCanvasUp, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCanvasUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageCanvasDown = lv_img_create(ui_PanelCanvas);
    lv_img_set_src(ui_ImageCanvasDown, &ui_img_button_down_png);
    lv_obj_set_width(ui_ImageCanvasDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCanvasDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageCanvasDown, 100);
    lv_obj_set_y(ui_ImageCanvasDown, 55);
    lv_obj_set_align(ui_ImageCanvasDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCanvasDown, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCanvasDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelCanvasMaskLarge = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasMaskLarge, 240);
    lv_obj_set_height(ui_PanelCanvasMaskLarge, 240);
    lv_obj_set_x(ui_PanelCanvasMaskLarge, -134);
    lv_obj_set_y(ui_PanelCanvasMaskLarge, 0);
    lv_obj_set_align(ui_PanelCanvasMaskLarge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasMaskLarge, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasMaskLarge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasMaskLarge, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasMaskLarge, lv_color_hex(0xD6D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasMaskLarge, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasMaskLarge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasMaskLarge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupCamera = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasPopupCamera, 212);
    lv_obj_set_height(ui_PanelCanvasPopupCamera, 213);
    lv_obj_set_x(ui_PanelCanvasPopupCamera, -1);
    lv_obj_set_y(ui_PanelCanvasPopupCamera, -3);
    lv_obj_set_align(ui_PanelCanvasPopupCamera, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasPopupCamera, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasPopupCamera, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasPopupCamera, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupCamera, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupCamera, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasPopupCamera, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasPopupCamera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupCameraTop = lv_label_create(ui_PanelCanvasPopupCamera);
    lv_obj_set_width(ui_LabelPanelCanvasPopupCameraTop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupCameraTop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupCameraTop, -2);
    lv_obj_set_y(ui_LabelPanelCanvasPopupCameraTop, -59);
    lv_obj_set_align(ui_LabelPanelCanvasPopupCameraTop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupCameraTop, "Camera Mode");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupCameraTop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupCameraTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);    
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupCameraTop, &ui_font_FontKoHoBold28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupCameraLine = lv_obj_create(ui_PanelCanvasPopupCamera);
    lv_obj_set_width(ui_PanelCanvasPopupCameraLine, 201);
    lv_obj_set_height(ui_PanelCanvasPopupCameraLine, 6);
    lv_obj_set_x(ui_PanelCanvasPopupCameraLine, -1);
    lv_obj_set_y(ui_PanelCanvasPopupCameraLine, -27);
    lv_obj_set_align(ui_PanelCanvasPopupCameraLine, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCanvasPopupCameraLine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupCameraLine, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupCameraLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupCameraDown = lv_label_create(ui_PanelCanvasPopupCamera);
    lv_obj_set_width(ui_LabelPanelCanvasPopupCameraDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupCameraDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupCameraDown, -1);
    lv_obj_set_y(ui_LabelPanelCanvasPopupCameraDown, 35);
    lv_obj_set_align(ui_LabelPanelCanvasPopupCameraDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupCameraDown, "Rotate wheel to\n   adjust zoom");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupCameraDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupCameraDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupCameraDown, &ui_font_FontKoHoMiniBold24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupAICamera = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasPopupAICamera, 212);
    lv_obj_set_height(ui_PanelCanvasPopupAICamera, 213);
    lv_obj_set_x(ui_PanelCanvasPopupAICamera, -1);
    lv_obj_set_y(ui_PanelCanvasPopupAICamera, -3);
    lv_obj_set_align(ui_PanelCanvasPopupAICamera, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasPopupAICamera, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasPopupAICamera, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasPopupAICamera, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupAICamera, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupAICamera, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasPopupAICamera, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasPopupAICamera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupAICameraTop = lv_label_create(ui_PanelCanvasPopupAICamera);
    lv_obj_set_width(ui_LabelPanelCanvasPopupAICameraTop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupAICameraTop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupAICameraTop, -2);
    lv_obj_set_y(ui_LabelPanelCanvasPopupAICameraTop, -59);
    lv_obj_set_align(ui_LabelPanelCanvasPopupAICameraTop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupAICameraTop, "AI Detect Mode");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupAICameraTop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupAICameraTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);    
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupAICameraTop, &ui_font_FontKoHoBold28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupAICameraLine = lv_obj_create(ui_PanelCanvasPopupAICamera);
    lv_obj_set_width(ui_PanelCanvasPopupAICameraLine, 201);
    lv_obj_set_height(ui_PanelCanvasPopupAICameraLine, 6);
    lv_obj_set_x(ui_PanelCanvasPopupAICameraLine, -1);
    lv_obj_set_y(ui_PanelCanvasPopupAICameraLine, -27);
    lv_obj_set_align(ui_PanelCanvasPopupAICameraLine, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCanvasPopupAICameraLine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupAICameraLine, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupAICameraLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupAICameraDown = lv_label_create(ui_PanelCanvasPopupAICamera);
    lv_obj_set_width(ui_LabelPanelCanvasPopupAICameraDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupAICameraDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupAICameraDown, -1);
    lv_obj_set_y(ui_LabelPanelCanvasPopupAICameraDown, 35);
    lv_obj_set_align(ui_LabelPanelCanvasPopupAICameraDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupAICameraDown, "Rotate wheel to\n   adjust zoom");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupAICameraDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupAICameraDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupAICameraDown, &ui_font_FontKoHoMiniBold24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageCanvasNOSDcard = lv_img_create(ui_PanelCanvas);
    lv_img_set_src(ui_ImageCanvasNOSDcard, &ui_img_sdcard_no_png);
    lv_obj_set_width(ui_ImageCanvasNOSDcard, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCanvasNOSDcard, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageCanvasNOSDcard, -102);
    lv_obj_set_y(ui_ImageCanvasNOSDcard, -101);
    lv_obj_set_align(ui_ImageCanvasNOSDcard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCanvasNOSDcard, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCanvasNOSDcard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageCanvasSDcard = lv_img_create(ui_PanelCanvas);
    lv_img_set_src(ui_ImageCanvasSDcard, &ui_img_sdcard_yes_png);
    lv_obj_set_width(ui_ImageCanvasSDcard, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCanvasSDcard, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageCanvasSDcard, -102);
    lv_obj_set_y(ui_ImageCanvasSDcard, -101);
    lv_obj_set_align(ui_ImageCanvasSDcard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCanvasSDcard, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCanvasSDcard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageCanvasMenu = lv_img_create(ui_PanelCanvas);
    lv_img_set_src(ui_ImageCanvasMenu, &ui_img_button_menu_png);
    lv_obj_set_width(ui_ImageCanvasMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCanvasMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageCanvasMenu, 100);
    lv_obj_set_y(ui_ImageCanvasMenu, -47);
    lv_obj_set_align(ui_ImageCanvasMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCanvasMenu, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCanvasMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCanvas2X = lv_label_create(ui_PanelCanvas);
    lv_obj_set_width(ui_LabelCanvas2X, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCanvas2X, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCanvas2X, 100);
    lv_obj_set_y(ui_LabelCanvas2X, 0);
    lv_obj_set_align(ui_LabelCanvas2X, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCanvas2X, "2X");
    lv_obj_add_flag(ui_LabelCanvas2X, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelCanvas2X, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCanvas2X, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCanvas2X, &ui_font_FontKoHoMiniBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCanvas3X = lv_label_create(ui_PanelCanvas);
    lv_obj_set_width(ui_LabelCanvas3X, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCanvas3X, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCanvas3X, 100);
    lv_obj_set_y(ui_LabelCanvas3X, 55);
    lv_obj_set_align(ui_LabelCanvas3X, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCanvas3X, "3X");
    lv_obj_add_flag(ui_LabelCanvas3X, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelCanvas3X, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCanvas3X, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCanvas3X, &ui_font_FontKoHoMiniBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCanvasFactor = lv_label_create(ui_PanelCanvas);
    lv_obj_set_width(ui_LabelCanvasFactor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCanvasFactor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCanvasFactor, 0);
    lv_obj_set_y(ui_LabelCanvasFactor, -100);
    lv_obj_set_align(ui_LabelCanvasFactor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCanvasFactor, "1X");
    lv_obj_add_flag(ui_LabelCanvasFactor, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelCanvasFactor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCanvasFactor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCanvasFactor, &ui_font_FontKoHoMiniBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasMaskCamera = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasMaskCamera, 100);
    lv_obj_set_height(ui_PanelCanvasMaskCamera, 87);
    lv_obj_set_x(ui_PanelCanvasMaskCamera, -120);
    lv_obj_set_y(ui_PanelCanvasMaskCamera, 0);
    lv_obj_set_align(ui_PanelCanvasMaskCamera, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasMaskCamera, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasMaskCamera, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasMaskCamera, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasMaskCamera, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasMaskCamera, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasMaskCamera, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasMaskCamera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImagePanelCanvasMaskCamera = lv_img_create(ui_PanelCanvasMaskCamera);
    lv_img_set_src(ui_ImagePanelCanvasMaskCamera, &ui_img_camera_small_png);
    lv_obj_set_width(ui_ImagePanelCanvasMaskCamera, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagePanelCanvasMaskCamera, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImagePanelCanvasMaskCamera, 20);
    lv_obj_set_y(ui_ImagePanelCanvasMaskCamera, 0);
    lv_obj_set_align(ui_ImagePanelCanvasMaskCamera, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImagePanelCanvasMaskCamera, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePanelCanvasMaskCamera, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelCanvasMaskAICamera = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasMaskAICamera, 100);
    lv_obj_set_height(ui_PanelCanvasMaskAICamera, 87);
    lv_obj_set_x(ui_PanelCanvasMaskAICamera, -120);
    lv_obj_set_y(ui_PanelCanvasMaskAICamera, 0);
    lv_obj_set_align(ui_PanelCanvasMaskAICamera, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasMaskAICamera, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasMaskAICamera, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasMaskAICamera, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasMaskAICamera, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasMaskAICamera, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasMaskAICamera, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasMaskAICamera, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImagePanelCanvasMaskAICamera = lv_img_create(ui_PanelCanvasMaskAICamera);
    lv_img_set_src(ui_ImagePanelCanvasMaskAICamera, &ui_img_ai_detect_small_png);
    lv_obj_set_width(ui_ImagePanelCanvasMaskAICamera, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagePanelCanvasMaskAICamera, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImagePanelCanvasMaskAICamera, 20);
    lv_obj_set_y(ui_ImagePanelCanvasMaskAICamera, 0);
    lv_obj_set_align(ui_ImagePanelCanvasMaskAICamera, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImagePanelCanvasMaskAICamera, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePanelCanvasMaskAICamera, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelCanvasPopupCameraInterval = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasPopupCameraInterval, 212);
    lv_obj_set_height(ui_PanelCanvasPopupCameraInterval, 212);
    lv_obj_set_x(ui_PanelCanvasPopupCameraInterval, -3);
    lv_obj_set_y(ui_PanelCanvasPopupCameraInterval, 0);
    lv_obj_set_align(ui_PanelCanvasPopupCameraInterval, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasPopupCameraInterval, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasPopupCameraInterval, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasPopupCameraInterval, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupCameraInterval, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupCameraInterval, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasPopupCameraInterval, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasPopupCameraInterval, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupCameraTopInterval = lv_label_create(ui_PanelCanvasPopupCameraInterval);
    lv_obj_set_width(ui_LabelPanelCanvasPopupCameraTopInterval, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupCameraTopInterval, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupCameraTopInterval, -4);
    lv_obj_set_y(ui_LabelPanelCanvasPopupCameraTopInterval, -59);
    lv_obj_set_align(ui_LabelPanelCanvasPopupCameraTopInterval, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupCameraTopInterval, "      Interval \n  Camera Mode");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupCameraTopInterval, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupCameraTopInterval, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupCameraTopInterval, &ui_font_FontKoHoBold28,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupCameraIntervalLine = lv_obj_create(ui_PanelCanvasPopupCameraInterval);
    lv_obj_set_width(ui_PanelCanvasPopupCameraIntervalLine, 200);
    lv_obj_set_height(ui_PanelCanvasPopupCameraIntervalLine, 6);
    lv_obj_set_x(ui_PanelCanvasPopupCameraIntervalLine, 0);
    lv_obj_set_y(ui_PanelCanvasPopupCameraIntervalLine, -14);
    lv_obj_set_align(ui_PanelCanvasPopupCameraIntervalLine, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCanvasPopupCameraIntervalLine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupCameraIntervalLine, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupCameraIntervalLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupCameraIntervalDown = lv_label_create(ui_PanelCanvasPopupCameraInterval);
    lv_obj_set_width(ui_LabelPanelCanvasPopupCameraIntervalDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupCameraIntervalDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupCameraIntervalDown, -1);
    lv_obj_set_y(ui_LabelPanelCanvasPopupCameraIntervalDown, 45);
    lv_obj_set_align(ui_LabelPanelCanvasPopupCameraIntervalDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupCameraIntervalDown, "1)  Set Interval\n2) Press wheel to \nstart shooting");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupCameraIntervalDown, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupCameraIntervalDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupCameraIntervalDown, &ui_font_FontKoHoMiniBold24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasMaskCameraInterval = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasMaskCameraInterval, 100);
    lv_obj_set_height(ui_PanelCanvasMaskCameraInterval, 87);
    lv_obj_set_x(ui_PanelCanvasMaskCameraInterval, -120);
    lv_obj_set_y(ui_PanelCanvasMaskCameraInterval, 0);
    lv_obj_set_align(ui_PanelCanvasMaskCameraInterval, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasMaskCameraInterval, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasMaskCameraInterval, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasMaskCameraInterval, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasMaskCameraInterval, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasMaskCameraInterval, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasMaskCameraInterval, lv_color_hex(0xC9C9C9),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasMaskCameraInterval, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImagePanelCanvasMaskCameraInterval = lv_img_create(ui_PanelCanvasMaskCameraInterval);
    lv_img_set_src(ui_ImagePanelCanvasMaskCameraInterval, &ui_img_interval_small_png);
    lv_obj_set_width(ui_ImagePanelCanvasMaskCameraInterval, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagePanelCanvasMaskCameraInterval, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImagePanelCanvasMaskCameraInterval, 20);
    lv_obj_set_y(ui_ImagePanelCanvasMaskCameraInterval, 0);
    lv_obj_set_align(ui_ImagePanelCanvasMaskCameraInterval, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImagePanelCanvasMaskCameraInterval, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePanelCanvasMaskCameraInterval, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCanvas5mplus = lv_label_create(ui_PanelCanvas);
    lv_obj_set_width(ui_LabelCanvas5mplus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCanvas5mplus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCanvas5mplus, 100);
    lv_obj_set_y(ui_LabelCanvas5mplus, 0);
    lv_obj_set_align(ui_LabelCanvas5mplus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCanvas5mplus, "+5m");
    lv_obj_add_flag(ui_LabelCanvas5mplus, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelCanvas5mplus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCanvas5mplus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCanvas5mplus, &ui_font_FontKoHoMiniBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCanvas5mSub = lv_label_create(ui_PanelCanvas);
    lv_obj_set_width(ui_LabelCanvas5mSub, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCanvas5mSub, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCanvas5mSub, 100);
    lv_obj_set_y(ui_LabelCanvas5mSub, 55);
    lv_obj_set_align(ui_LabelCanvas5mSub, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCanvas5mSub, "-5m");
    lv_obj_add_flag(ui_LabelCanvas5mSub, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelCanvas5mSub, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCanvas5mSub, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCanvas5mSub, &ui_font_FontKoHoMiniBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCanvasInvervalTime = lv_label_create(ui_PanelCanvas);
    lv_obj_set_width(ui_LabelCanvasInvervalTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCanvasInvervalTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCanvasInvervalTime, -90);
    lv_obj_set_y(ui_LabelCanvasInvervalTime, 100);
    lv_obj_set_align(ui_LabelCanvasInvervalTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCanvasInvervalTime, "30min");
    lv_obj_add_flag(ui_LabelCanvasInvervalTime, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelCanvasInvervalTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCanvasInvervalTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCanvasInvervalTime, &ui_font_FontKoHoMiniBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupVideoMode = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasPopupVideoMode, 212);
    lv_obj_set_height(ui_PanelCanvasPopupVideoMode, 212);
    lv_obj_set_x(ui_PanelCanvasPopupVideoMode, -2);
    lv_obj_set_y(ui_PanelCanvasPopupVideoMode, -1);
    lv_obj_set_align(ui_PanelCanvasPopupVideoMode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasPopupVideoMode, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasPopupVideoMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasPopupVideoMode, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupVideoMode, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupVideoMode, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasPopupVideoMode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasPopupVideoMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupVideoModeTop = lv_label_create(ui_PanelCanvasPopupVideoMode);
    lv_obj_set_width(ui_LabelPanelCanvasPopupVideoModeTop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupVideoModeTop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupVideoModeTop, -1);
    lv_obj_set_y(ui_LabelPanelCanvasPopupVideoModeTop, -66);
    lv_obj_set_align(ui_LabelPanelCanvasPopupVideoModeTop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupVideoModeTop, "Video Mode");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupVideoModeTop, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupVideoModeTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupVideoModeTop, &ui_font_FontKoHoBold28,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupVideoModeLine = lv_obj_create(ui_PanelCanvasPopupVideoMode);
    lv_obj_set_width(ui_PanelCanvasPopupVideoModeLine, 183);
    lv_obj_set_height(ui_PanelCanvasPopupVideoModeLine, 6);
    lv_obj_set_x(ui_PanelCanvasPopupVideoModeLine, -3);
    lv_obj_set_y(ui_PanelCanvasPopupVideoModeLine, -32);
    lv_obj_set_align(ui_PanelCanvasPopupVideoModeLine, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCanvasPopupVideoModeLine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupVideoModeLine, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupVideoModeLine, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupVideoModeDown = lv_label_create(ui_PanelCanvasPopupVideoMode);
    lv_obj_set_width(ui_LabelPanelCanvasPopupVideoModeDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupVideoModeDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupVideoModeDown, 1);
    lv_obj_set_y(ui_LabelPanelCanvasPopupVideoModeDown, 32);
    lv_obj_set_align(ui_LabelPanelCanvasPopupVideoModeDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupVideoModeDown, "Rotate wheel to \n  adjust zoom.");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupVideoModeDown, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupVideoModeDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupVideoModeDown, &ui_font_FontKoHoMiniBold24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasMaskVideoMode = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasMaskVideoMode, 100);
    lv_obj_set_height(ui_PanelCanvasMaskVideoMode, 87);
    lv_obj_set_x(ui_PanelCanvasMaskVideoMode, -120);
    lv_obj_set_y(ui_PanelCanvasMaskVideoMode, 0);
    lv_obj_set_align(ui_PanelCanvasMaskVideoMode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasMaskVideoMode, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasMaskVideoMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasMaskVideoMode, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasMaskVideoMode, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasMaskVideoMode, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasMaskVideoMode, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasMaskVideoMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImagePanelCanvasMaskVideoMode = lv_img_create(ui_PanelCanvasMaskVideoMode);
    lv_img_set_src(ui_ImagePanelCanvasMaskVideoMode, &ui_img_video_small_png);
    lv_obj_set_width(ui_ImagePanelCanvasMaskVideoMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagePanelCanvasMaskVideoMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImagePanelCanvasMaskVideoMode, 20);
    lv_obj_set_y(ui_ImagePanelCanvasMaskVideoMode, 0);
    lv_obj_set_align(ui_ImagePanelCanvasMaskVideoMode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImagePanelCanvasMaskVideoMode, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePanelCanvasMaskVideoMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelCanvasPopupSDWarning = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasPopupSDWarning, 212);
    lv_obj_set_height(ui_PanelCanvasPopupSDWarning, 212);
    lv_obj_set_x(ui_PanelCanvasPopupSDWarning, -2);
    lv_obj_set_y(ui_PanelCanvasPopupSDWarning, -4);
    lv_obj_set_align(ui_PanelCanvasPopupSDWarning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasPopupSDWarning, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasPopupSDWarning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasPopupSDWarning, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupSDWarning, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupSDWarning, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasPopupSDWarning, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasPopupSDWarning, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupSDWarning = lv_label_create(ui_PanelCanvasPopupSDWarning);
    lv_obj_set_width(ui_LabelPanelCanvasPopupSDWarning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupSDWarning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupSDWarning, -4);
    lv_obj_set_y(ui_LabelPanelCanvasPopupSDWarning, -70);
    lv_obj_set_align(ui_LabelPanelCanvasPopupSDWarning, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupSDWarning, "Warning");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupSDWarning, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupSDWarning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupSDWarning, &ui_font_FontKoHoBold28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupCameraSDWarning = lv_obj_create(ui_PanelCanvasPopupSDWarning);
    lv_obj_set_width(ui_PanelCanvasPopupCameraSDWarning, 197);
    lv_obj_set_height(ui_PanelCanvasPopupCameraSDWarning, 6);
    lv_obj_set_x(ui_PanelCanvasPopupCameraSDWarning, -1);
    lv_obj_set_y(ui_PanelCanvasPopupCameraSDWarning, -36);
    lv_obj_set_align(ui_PanelCanvasPopupCameraSDWarning, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCanvasPopupCameraSDWarning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupCameraSDWarning, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupCameraSDWarning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupCameraSDWarning = lv_label_create(ui_PanelCanvasPopupSDWarning);
    lv_obj_set_width(ui_LabelPanelCanvasPopupCameraSDWarning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupCameraSDWarning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupCameraSDWarning, 3);
    lv_obj_set_y(ui_LabelPanelCanvasPopupCameraSDWarning, 39);
    lv_obj_set_align(ui_LabelPanelCanvasPopupCameraSDWarning, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupCameraSDWarning,
                      "No SD card detected\n\n  Insert SD Card to \n          continue");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupCameraSDWarning, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupCameraSDWarning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupCameraSDWarning, &ui_font_FontKoHoMiniBold22,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupIntervalTimerWarning = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasPopupIntervalTimerWarning, 212);
    lv_obj_set_height(ui_PanelCanvasPopupIntervalTimerWarning, 212);
    lv_obj_set_x(ui_PanelCanvasPopupIntervalTimerWarning, -3);
    lv_obj_set_y(ui_PanelCanvasPopupIntervalTimerWarning, 0);
    lv_obj_set_align(ui_PanelCanvasPopupIntervalTimerWarning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasPopupIntervalTimerWarning, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasPopupIntervalTimerWarning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasPopupIntervalTimerWarning, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupIntervalTimerWarning, lv_color_hex(0xC9C9C9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupIntervalTimerWarning, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasPopupIntervalTimerWarning, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasPopupIntervalTimerWarning, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupIntervalTimerWarning = lv_label_create(ui_PanelCanvasPopupIntervalTimerWarning);
    lv_obj_set_width(ui_LabelPanelCanvasPopupIntervalTimerWarning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupIntervalTimerWarning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupIntervalTimerWarning, -1);
    lv_obj_set_y(ui_LabelPanelCanvasPopupIntervalTimerWarning, -38);
    lv_obj_set_align(ui_LabelPanelCanvasPopupIntervalTimerWarning, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupIntervalTimerWarning, "Interval Cam");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupIntervalTimerWarning, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupIntervalTimerWarning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupIntervalTimerWarning, &ui_font_FontKoHoBold28,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupCameraIntervalTimerWarning = lv_obj_create(ui_PanelCanvasPopupIntervalTimerWarning);
    lv_obj_set_width(ui_PanelCanvasPopupCameraIntervalTimerWarning, 199);
    lv_obj_set_height(ui_PanelCanvasPopupCameraIntervalTimerWarning, 6);
    lv_obj_set_x(ui_PanelCanvasPopupCameraIntervalTimerWarning, 0);
    lv_obj_set_y(ui_PanelCanvasPopupCameraIntervalTimerWarning, -13);
    lv_obj_set_align(ui_PanelCanvasPopupCameraIntervalTimerWarning, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCanvasPopupCameraIntervalTimerWarning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupCameraIntervalTimerWarning, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupCameraIntervalTimerWarning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupCameraIntervalTimerWarning = lv_label_create(ui_PanelCanvasPopupIntervalTimerWarning);
    lv_obj_set_width(ui_LabelPanelCanvasPopupCameraIntervalTimerWarning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupCameraIntervalTimerWarning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupCameraIntervalTimerWarning, 0);
    lv_obj_set_y(ui_LabelPanelCanvasPopupCameraIntervalTimerWarning, 58);
    lv_obj_set_align(ui_LabelPanelCanvasPopupCameraIntervalTimerWarning, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupCameraIntervalTimerWarning,
                      "   Display will be \n        dimmed\nPress any button to\n  end interval cam\n");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupCameraIntervalTimerWarning, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupCameraIntervalTimerWarning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupCameraIntervalTimerWarning, &ui_font_FontKoHoMiniBold22,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupIntervalTimer = lv_label_create(ui_PanelCanvasPopupIntervalTimerWarning);
    lv_obj_set_width(ui_LabelPanelCanvasPopupIntervalTimer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupIntervalTimer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupIntervalTimer, 1);
    lv_obj_set_y(ui_LabelPanelCanvasPopupIntervalTimer, -74);
    lv_obj_set_align(ui_LabelPanelCanvasPopupIntervalTimer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupIntervalTimer, "Starting 30 min");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupIntervalTimer, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupIntervalTimer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupIntervalTimer, &ui_font_FontKoHoBold28,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupIntervalTimerWarningEnd = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasPopupIntervalTimerWarningEnd, 212);
    lv_obj_set_height(ui_PanelCanvasPopupIntervalTimerWarningEnd, 212);
    lv_obj_set_x(ui_PanelCanvasPopupIntervalTimerWarningEnd, -3);
    lv_obj_set_y(ui_PanelCanvasPopupIntervalTimerWarningEnd, -3);
    lv_obj_set_align(ui_PanelCanvasPopupIntervalTimerWarningEnd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasPopupIntervalTimerWarningEnd, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasPopupIntervalTimerWarningEnd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasPopupIntervalTimerWarningEnd, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupIntervalTimerWarningEnd, lv_color_hex(0xC9C9C9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupIntervalTimerWarningEnd, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasPopupIntervalTimerWarningEnd, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasPopupIntervalTimerWarningEnd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupIntervalTimerWarningEnd = lv_label_create(ui_PanelCanvasPopupIntervalTimerWarningEnd);
    lv_obj_set_width(ui_LabelPanelCanvasPopupIntervalTimerWarningEnd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupIntervalTimerWarningEnd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupIntervalTimerWarningEnd, 1);
    lv_obj_set_y(ui_LabelPanelCanvasPopupIntervalTimerWarningEnd, -23);
    lv_obj_set_align(ui_LabelPanelCanvasPopupIntervalTimerWarningEnd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupIntervalTimerWarningEnd, "Interval Cam");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupIntervalTimerWarningEnd, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupIntervalTimerWarningEnd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupIntervalTimerWarningEnd, &ui_font_FontKoHoBold28,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupCameraIntervalTimerWarningEnd = lv_obj_create(ui_PanelCanvasPopupIntervalTimerWarningEnd);
    lv_obj_set_width(ui_PanelCanvasPopupCameraIntervalTimerWarningEnd, 194);
    lv_obj_set_height(ui_PanelCanvasPopupCameraIntervalTimerWarningEnd, 6);
    lv_obj_set_x(ui_PanelCanvasPopupCameraIntervalTimerWarningEnd, 1);
    lv_obj_set_y(ui_PanelCanvasPopupCameraIntervalTimerWarningEnd, 10);
    lv_obj_set_align(ui_PanelCanvasPopupCameraIntervalTimerWarningEnd, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCanvasPopupCameraIntervalTimerWarningEnd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupCameraIntervalTimerWarningEnd, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupCameraIntervalTimerWarningEnd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupCameraIntervalTimerWarningEnd = lv_label_create(ui_PanelCanvasPopupIntervalTimerWarningEnd);
    lv_obj_set_width(ui_LabelPanelCanvasPopupCameraIntervalTimerWarningEnd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupCameraIntervalTimerWarningEnd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupCameraIntervalTimerWarningEnd, 4);
    lv_obj_set_y(ui_LabelPanelCanvasPopupCameraIntervalTimerWarningEnd, 61);
    lv_obj_set_align(ui_LabelPanelCanvasPopupCameraIntervalTimerWarningEnd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupCameraIntervalTimerWarningEnd, "3 photos saved to \n       SD Card");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupCameraIntervalTimerWarningEnd, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupCameraIntervalTimerWarningEnd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupCameraIntervalTimerWarningEnd, &ui_font_FontKoHoMiniBold22,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupIntervalTimerEnd = lv_label_create(ui_PanelCanvasPopupIntervalTimerWarningEnd);
    lv_obj_set_width(ui_LabelPanelCanvasPopupIntervalTimerEnd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupIntervalTimerEnd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupIntervalTimerEnd, 1);
    lv_obj_set_y(ui_LabelPanelCanvasPopupIntervalTimerEnd, -67);
    lv_obj_set_align(ui_LabelPanelCanvasPopupIntervalTimerEnd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupIntervalTimerEnd, "Ended 30 min");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupIntervalTimerEnd, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupIntervalTimerEnd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupIntervalTimerEnd, &ui_font_FontKoHoBold28,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageRedDot = lv_img_create(ui_PanelCanvas);
    lv_img_set_src(ui_ImageRedDot, &ui_img_reddot_recording_png);
    lv_obj_set_width(ui_ImageRedDot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageRedDot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageRedDot, 102);
    lv_obj_set_y(ui_ImageRedDot, -102);
    lv_obj_set_align(ui_ImageRedDot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageRedDot, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageRedDot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelRedDotTime = lv_label_create(ui_PanelCanvas);
    lv_obj_set_width(ui_LabelRedDotTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRedDotTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRedDotTime, 69);
    lv_obj_set_y(ui_LabelRedDotTime, -102);
    lv_obj_set_align(ui_LabelRedDotTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRedDotTime, "22:22");
    lv_obj_add_flag(ui_LabelRedDotTime, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelRedDotTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelRedDotTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSettings = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelSettings, 183);
    lv_obj_set_height(ui_PanelSettings, 170);
    lv_obj_set_x(ui_PanelSettings, -14);
    lv_obj_set_y(ui_PanelSettings, -16);
    lv_obj_set_align(ui_PanelSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelSettings, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSettings, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSettings, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSettings, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelSettings = lv_label_create(ui_PanelSettings);
    lv_obj_set_width(ui_LabelPanelSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelSettings, 0);
    lv_obj_set_y(ui_LabelPanelSettings, -72);
    lv_obj_set_align(ui_LabelPanelSettings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelSettings, "Settings");
    lv_obj_set_style_text_color(ui_LabelPanelSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelSettings, &ui_font_FontKoHoBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPanelSettingsGyroscope = lv_obj_create(ui_PanelSettings);
    lv_obj_set_width(ui_PanelPanelSettingsGyroscope, 172);
    lv_obj_set_height(ui_PanelPanelSettingsGyroscope, 30);
    lv_obj_set_x(ui_PanelPanelSettingsGyroscope, 1);
    lv_obj_set_y(ui_PanelPanelSettingsGyroscope, -45);
    lv_obj_set_align(ui_PanelPanelSettingsGyroscope, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPanelSettingsGyroscope, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelPanelSettingsGyroscope, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPanelSettingsGyroscope, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPanelSettingsGyroscope, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPanelSettingsGyroscope, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPanelSettingsGyroscope, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPanelSettingsGyroscope, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_PanelPanelSettingsGyroscope, 100, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelPanelPanelSettingsGyroscopeItem = lv_label_create(ui_PanelPanelSettingsGyroscope);
    lv_obj_set_width(ui_LabelPanelPanelSettingsGyroscopeItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelPanelSettingsGyroscopeItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelPanelSettingsGyroscopeItem, -26);
    lv_obj_set_y(ui_LabelPanelPanelSettingsGyroscopeItem, 0);
    lv_obj_set_align(ui_LabelPanelPanelSettingsGyroscopeItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelPanelSettingsGyroscopeItem, "Display Rotate");
    lv_obj_set_style_text_color(ui_LabelPanelPanelSettingsGyroscopeItem, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelPanelSettingsGyroscopeItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelPanelSettingsGyroscopeItem, &ui_font_FontKoHoMiniBold18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelPanelSettingsGyroscopeBody = lv_label_create(ui_PanelPanelSettingsGyroscope);
    lv_obj_set_width(ui_LabelPanelPanelSettingsGyroscopeBody, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelPanelSettingsGyroscopeBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelPanelSettingsGyroscopeBody, 55);
    lv_obj_set_y(ui_LabelPanelPanelSettingsGyroscopeBody, 0);
    lv_obj_set_align(ui_LabelPanelPanelSettingsGyroscopeBody, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelPanelSettingsGyroscopeBody, "Off");
    lv_obj_set_style_text_color(ui_LabelPanelPanelSettingsGyroscopeBody, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelPanelSettingsGyroscopeBody, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelPanelSettingsGyroscopeBody, &ui_font_FontKoHoMiniBold18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPanelSettingsLanguage = lv_obj_create(ui_PanelSettings);
    lv_obj_set_width(ui_PanelPanelSettingsLanguage, 172);
    lv_obj_set_height(ui_PanelPanelSettingsLanguage, 30);
    lv_obj_set_x(ui_PanelPanelSettingsLanguage, 1);
    lv_obj_set_y(ui_PanelPanelSettingsLanguage, -10);
    lv_obj_set_align(ui_PanelPanelSettingsLanguage, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPanelSettingsLanguage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelPanelSettingsLanguage, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPanelSettingsLanguage, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPanelSettingsLanguage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPanelSettingsLanguage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPanelSettingsLanguage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPanelSettingsLanguage, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_PanelPanelSettingsLanguage, 100, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelPanelPanelSettingsODItem = lv_label_create(ui_PanelPanelSettingsLanguage);
    lv_obj_set_width(ui_LabelPanelPanelSettingsODItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelPanelSettingsODItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelPanelSettingsODItem, -28);
    lv_obj_set_y(ui_LabelPanelPanelSettingsODItem, 0);
    lv_obj_set_align(ui_LabelPanelPanelSettingsODItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelPanelSettingsODItem, "Obj Det(YOLO)");
    lv_obj_set_style_text_color(ui_LabelPanelPanelSettingsODItem, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelPanelSettingsODItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelPanelSettingsODItem, &ui_font_FontKoHoMiniBold18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelPanelSettingsODBody = lv_label_create(ui_PanelPanelSettingsLanguage);
    lv_obj_set_width(ui_LabelPanelPanelSettingsODBody, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelPanelSettingsODBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelPanelSettingsODBody, 55);
    lv_obj_set_y(ui_LabelPanelPanelSettingsODBody, 0);
    lv_obj_set_align(ui_LabelPanelPanelSettingsODBody, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelPanelSettingsODBody, "Off");
    lv_obj_set_style_text_color(ui_LabelPanelPanelSettingsODBody, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelPanelSettingsODBody, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelPanelSettingsODBody, &ui_font_FontKoHoMiniBold18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPanelSettingsRes = lv_obj_create(ui_PanelSettings);
    lv_obj_set_width(ui_PanelPanelSettingsRes, 172);
    lv_obj_set_height(ui_PanelPanelSettingsRes, 27);
    lv_obj_set_x(ui_PanelPanelSettingsRes, 0);
    lv_obj_set_y(ui_PanelPanelSettingsRes, 25);
    lv_obj_set_align(ui_PanelPanelSettingsRes, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPanelSettingsRes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelPanelSettingsRes, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPanelSettingsRes, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPanelSettingsRes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPanelSettingsRes, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPanelSettingsRes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPanelSettingsRes, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_PanelPanelSettingsRes, 100, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelPanelPanelSettingsResItem = lv_label_create(ui_PanelPanelSettingsRes);
    lv_obj_set_width(ui_LabelPanelPanelSettingsResItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelPanelSettingsResItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelPanelSettingsResItem, -43);
    lv_obj_set_y(ui_LabelPanelPanelSettingsResItem, 0);
    lv_obj_set_align(ui_LabelPanelPanelSettingsResItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelPanelSettingsResItem, "Resolution");
    lv_obj_set_style_text_color(ui_LabelPanelPanelSettingsResItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelPanelSettingsResItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelPanelSettingsResItem, &ui_font_FontKoHoMiniBold18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelPanelSettingsResBody = lv_label_create(ui_PanelPanelSettingsRes);
    lv_obj_set_width(ui_LabelPanelPanelSettingsResBody, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelPanelSettingsResBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelPanelSettingsResBody, 55);
    lv_obj_set_y(ui_LabelPanelPanelSettingsResBody, 0);
    lv_obj_set_align(ui_LabelPanelPanelSettingsResBody, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelPanelSettingsResBody, "720P");
    lv_obj_set_style_text_color(ui_LabelPanelPanelSettingsResBody, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelPanelSettingsResBody, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelPanelSettingsResBody, &ui_font_FontKoHoMiniBold18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPanelSettingsFlash = lv_obj_create(ui_PanelSettings);
    lv_obj_set_width(ui_PanelPanelSettingsFlash, 172);
    lv_obj_set_height(ui_PanelPanelSettingsFlash, 27);
    lv_obj_set_x(ui_PanelPanelSettingsFlash, 0);
    lv_obj_set_y(ui_PanelPanelSettingsFlash, 60);
    lv_obj_set_align(ui_PanelPanelSettingsFlash, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPanelSettingsFlash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelPanelSettingsFlash, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPanelSettingsFlash, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPanelSettingsFlash, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPanelSettingsFlash, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPanelSettingsFlash, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPanelSettingsFlash, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_PanelPanelSettingsFlash, 100, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelPanelPanelSettingsFlashItem = lv_label_create(ui_PanelPanelSettingsFlash);
    lv_obj_set_width(ui_LabelPanelPanelSettingsFlashItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelPanelSettingsFlashItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelPanelSettingsFlashItem, -43);
    lv_obj_set_y(ui_LabelPanelPanelSettingsFlashItem, 0);
    lv_obj_set_align(ui_LabelPanelPanelSettingsFlashItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelPanelSettingsFlashItem, "Flash");
    lv_obj_set_style_text_color(ui_LabelPanelPanelSettingsFlashItem, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelPanelSettingsFlashItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelPanelSettingsFlashItem, &ui_font_FontKoHoMiniBold18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelPanelSettingsFlashBody = lv_label_create(ui_PanelPanelSettingsFlash);
    lv_obj_set_width(ui_LabelPanelPanelSettingsFlashBody, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelPanelSettingsFlashBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelPanelSettingsFlashBody, 55);
    lv_obj_set_y(ui_LabelPanelPanelSettingsFlashBody, 0);
    lv_obj_set_align(ui_LabelPanelPanelSettingsFlashBody, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelPanelSettingsFlashBody, "Off");
    lv_obj_set_style_text_color(ui_LabelPanelPanelSettingsFlashBody, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelPanelSettingsFlashBody, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelPanelSettingsFlashBody, &ui_font_FontKoHoMiniBold18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSettingsMenu = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelSettingsMenu, 181);
    lv_obj_set_height(ui_PanelSettingsMenu, 33);
    lv_obj_set_x(ui_PanelSettingsMenu, -12);
    lv_obj_set_y(ui_PanelSettingsMenu, 92);
    lv_obj_set_align(ui_PanelSettingsMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelSettingsMenu, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelSettingsMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSettingsMenu, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSettingsMenu, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSettingsMenu, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelSettingsMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSettingsMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSettingsMenu, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_PanelSettingsMenu, 120, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelPanelSettingsMenu = lv_label_create(ui_PanelSettingsMenu);
    lv_obj_set_width(ui_LabelPanelSettingsMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelSettingsMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelSettingsMenu, 0);
    lv_obj_set_y(ui_LabelPanelSettingsMenu, 1);
    lv_obj_set_align(ui_LabelPanelSettingsMenu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelSettingsMenu, "Back to Menu");
    lv_obj_set_style_text_color(ui_LabelPanelSettingsMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelSettingsMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelSettingsMenu, &ui_font_FontKoHoMiniBold18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelInrervalTimePrompt = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelInrervalTimePrompt, 125);
    lv_obj_set_height(ui_PanelInrervalTimePrompt, 50);
    lv_obj_set_x(ui_PanelInrervalTimePrompt, 3);
    lv_obj_set_y(ui_PanelInrervalTimePrompt, 1);
    lv_obj_set_align(ui_PanelInrervalTimePrompt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelInrervalTimePrompt, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelInrervalTimePrompt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelInrervalTimePrompt, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelInrervalTimePrompt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelInrervalTimePrompt, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelInrervalTimePrompt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelInrervalTimePrompt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelInrervalTimePrompt = lv_label_create(ui_PanelInrervalTimePrompt);
    lv_obj_set_width(ui_LabelPanelInrervalTimePrompt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelInrervalTimePrompt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelInrervalTimePrompt, -20);
    lv_obj_set_y(ui_LabelPanelInrervalTimePrompt, 0);
    lv_obj_set_align(ui_LabelPanelInrervalTimePrompt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelInrervalTimePrompt, "30");
    lv_obj_set_style_text_color(ui_LabelPanelInrervalTimePrompt, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelInrervalTimePrompt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelInrervalTimePrompt, &ui_font_FontKoHoMiniBold24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelInrervalTimePromptMin = lv_label_create(ui_PanelInrervalTimePrompt);
    lv_obj_set_width(ui_LabelPanelInrervalTimePromptMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelInrervalTimePromptMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelInrervalTimePromptMin, 21);
    lv_obj_set_y(ui_LabelPanelInrervalTimePromptMin, -2);
    lv_obj_set_align(ui_LabelPanelInrervalTimePromptMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelInrervalTimePromptMin, "min");
    lv_obj_set_style_text_font(ui_LabelPanelInrervalTimePromptMin, &ui_font_FontKoHoMiniBold24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelPanelInrervalTimePromptMin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelPanelInrervalTimePromptMin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupSDSpaceWarning = lv_obj_create(ui_PanelCanvas);
    lv_obj_set_width(ui_PanelCanvasPopupSDSpaceWarning, 212);
    lv_obj_set_height(ui_PanelCanvasPopupSDSpaceWarning, 212);
    lv_obj_set_x(ui_PanelCanvasPopupSDSpaceWarning, -2);
    lv_obj_set_y(ui_PanelCanvasPopupSDSpaceWarning, -4);
    lv_obj_set_align(ui_PanelCanvasPopupSDSpaceWarning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCanvasPopupSDSpaceWarning, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCanvasPopupSDSpaceWarning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCanvasPopupSDSpaceWarning, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupSDSpaceWarning, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupSDSpaceWarning, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCanvasPopupSDSpaceWarning, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCanvasPopupSDSpaceWarning, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupSDSpaceWarning = lv_label_create(ui_PanelCanvasPopupSDSpaceWarning);
    lv_obj_set_width(ui_LabelPanelCanvasPopupSDSpaceWarning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupSDSpaceWarning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupSDSpaceWarning, -4);
    lv_obj_set_y(ui_LabelPanelCanvasPopupSDSpaceWarning, -70);
    lv_obj_set_align(ui_LabelPanelCanvasPopupSDSpaceWarning, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupSDSpaceWarning, "Warning");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupSDSpaceWarning, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupSDSpaceWarning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupSDSpaceWarning, &ui_font_FontKoHoBold28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCanvasPopupCameraSDSpaceWarning = lv_obj_create(ui_PanelCanvasPopupSDSpaceWarning);
    lv_obj_set_width(ui_PanelCanvasPopupCameraSDSpaceWarning, 197);
    lv_obj_set_height(ui_PanelCanvasPopupCameraSDSpaceWarning, 6);
    lv_obj_set_x(ui_PanelCanvasPopupCameraSDSpaceWarning, -1);
    lv_obj_set_y(ui_PanelCanvasPopupCameraSDSpaceWarning, -36);
    lv_obj_set_align(ui_PanelCanvasPopupCameraSDSpaceWarning, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCanvasPopupCameraSDSpaceWarning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCanvasPopupCameraSDSpaceWarning, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCanvasPopupCameraSDSpaceWarning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPanelCanvasPopupCameraSDSpaceWarning = lv_label_create(ui_PanelCanvasPopupSDSpaceWarning);
    lv_obj_set_width(ui_LabelPanelCanvasPopupCameraSDSpaceWarning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelCanvasPopupCameraSDSpaceWarning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelCanvasPopupCameraSDSpaceWarning, 3);
    lv_obj_set_y(ui_LabelPanelCanvasPopupCameraSDSpaceWarning, 39);
    lv_obj_set_align(ui_LabelPanelCanvasPopupCameraSDSpaceWarning, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelCanvasPopupCameraSDSpaceWarning,
                      "   Insufficient \n\n SD card space!");
    lv_obj_set_style_text_color(ui_LabelPanelCanvasPopupCameraSDSpaceWarning, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelCanvasPopupCameraSDSpaceWarning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelCanvasPopupCameraSDSpaceWarning, &ui_font_FontKoHoMiniBold22,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCameraSettings = lv_obj_create(ui_ScreenCamera);
    lv_obj_set_width(ui_PanelCameraSettings, 183);
    lv_obj_set_height(ui_PanelCameraSettings, 170);
    lv_obj_set_x(ui_PanelCameraSettings, -14);
    lv_obj_set_y(ui_PanelCameraSettings, -16);
    lv_obj_set_align(ui_PanelCameraSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelCameraSettings, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelCameraSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCameraSettings, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCameraSettings, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCameraSettings, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCameraSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCameraSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPanelSettingsContrast = lv_obj_create(ui_PanelCameraSettings);
    lv_obj_set_width(ui_PanelPanelSettingsContrast, 172);
    lv_obj_set_height(ui_PanelPanelSettingsContrast, 30);
    lv_obj_set_x(ui_PanelPanelSettingsContrast, 0);
    lv_obj_set_y(ui_PanelPanelSettingsContrast, -55);
    lv_obj_set_align(ui_PanelPanelSettingsContrast, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPanelSettingsContrast, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelPanelSettingsContrast, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPanelSettingsContrast, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPanelSettingsContrast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPanelSettingsContrast, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPanelSettingsContrast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPanelSettingsContrast, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_PanelPanelSettingsContrast, 100, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelPanelPanelSettingsContrast = lv_label_create(ui_PanelPanelSettingsContrast);
    lv_obj_set_width(ui_LabelPanelPanelSettingsContrast, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelPanelSettingsContrast, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelPanelSettingsContrast, -49);
    lv_obj_set_y(ui_LabelPanelPanelSettingsContrast, 0);
    lv_obj_set_align(ui_LabelPanelPanelSettingsContrast, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelPanelSettingsContrast, "Contrast");
    lv_obj_set_style_text_color(ui_LabelPanelPanelSettingsContrast, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelPanelSettingsContrast, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelPanelSettingsContrast, &ui_font_FontKoHoMiniBold14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderPanelPanelSettingsContrast = lv_slider_create(ui_PanelPanelSettingsContrast);
    lv_slider_set_value(ui_SliderPanelPanelSettingsContrast, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderPanelPanelSettingsContrast) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderPanelPanelSettingsContrast, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderPanelPanelSettingsContrast, 84);
    lv_obj_set_height(ui_SliderPanelPanelSettingsContrast, 2);
    lv_obj_set_x(ui_SliderPanelPanelSettingsContrast, 38);
    lv_obj_set_y(ui_SliderPanelPanelSettingsContrast, 0);
    lv_obj_set_align(ui_SliderPanelPanelSettingsContrast, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SliderPanelPanelSettingsContrast, lv_color_hex(0x000000),
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPanelPanelSettingsContrast, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderPanelPanelSettingsContrast, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPanelPanelSettingsContrast, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_PanelPanelSettingsSaturation = lv_obj_create(ui_PanelCameraSettings);
    lv_obj_set_width(ui_PanelPanelSettingsSaturation, 172);
    lv_obj_set_height(ui_PanelPanelSettingsSaturation, 30);
    lv_obj_set_x(ui_PanelPanelSettingsSaturation, 0);
    lv_obj_set_y(ui_PanelPanelSettingsSaturation, -15);
    lv_obj_set_align(ui_PanelPanelSettingsSaturation, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPanelSettingsSaturation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelPanelSettingsSaturation, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPanelSettingsSaturation, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPanelSettingsSaturation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPanelSettingsSaturation, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPanelSettingsSaturation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPanelSettingsSaturation, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_PanelPanelSettingsSaturation, 100, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelPanelPanelSettingsSaturation = lv_label_create(ui_PanelPanelSettingsSaturation);
    lv_obj_set_width(ui_LabelPanelPanelSettingsSaturation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelPanelSettingsSaturation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelPanelSettingsSaturation, -49);
    lv_obj_set_y(ui_LabelPanelPanelSettingsSaturation, 0);
    lv_obj_set_align(ui_LabelPanelPanelSettingsSaturation, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelPanelSettingsSaturation, "Saturation");
    lv_obj_set_style_text_color(ui_LabelPanelPanelSettingsSaturation, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelPanelSettingsSaturation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelPanelSettingsSaturation, &ui_font_FontKoHoMiniBold14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderPanelPanelSettingsSaturation = lv_slider_create(ui_PanelPanelSettingsSaturation);
    lv_slider_set_value(ui_SliderPanelPanelSettingsSaturation, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderPanelPanelSettingsSaturation) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderPanelPanelSettingsSaturation, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderPanelPanelSettingsSaturation, 84);
    lv_obj_set_height(ui_SliderPanelPanelSettingsSaturation, 2);
    lv_obj_set_x(ui_SliderPanelPanelSettingsSaturation, 38);
    lv_obj_set_y(ui_SliderPanelPanelSettingsSaturation, 0);
    lv_obj_set_align(ui_SliderPanelPanelSettingsSaturation, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SliderPanelPanelSettingsSaturation, lv_color_hex(0x000000),
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPanelPanelSettingsSaturation, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderPanelPanelSettingsSaturation, lv_color_hex(0x000000),
                              LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPanelPanelSettingsSaturation, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_PanelPanelSettingsBrightness = lv_obj_create(ui_PanelCameraSettings);
    lv_obj_set_width(ui_PanelPanelSettingsBrightness, 172);
    lv_obj_set_height(ui_PanelPanelSettingsBrightness, 30);
    lv_obj_set_x(ui_PanelPanelSettingsBrightness, 0);
    lv_obj_set_y(ui_PanelPanelSettingsBrightness, 25);
    lv_obj_set_align(ui_PanelPanelSettingsBrightness, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPanelSettingsBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelPanelSettingsBrightness, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPanelSettingsBrightness, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPanelSettingsBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPanelSettingsBrightness, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPanelSettingsBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPanelSettingsBrightness, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_PanelPanelSettingsBrightness, 100, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelPanelPanelSettingsBrightness = lv_label_create(ui_PanelPanelSettingsBrightness);
    lv_obj_set_width(ui_LabelPanelPanelSettingsBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelPanelSettingsBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelPanelSettingsBrightness, -49);
    lv_obj_set_y(ui_LabelPanelPanelSettingsBrightness, 0);
    lv_obj_set_align(ui_LabelPanelPanelSettingsBrightness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelPanelSettingsBrightness, "Brightness");
    lv_obj_set_style_text_color(ui_LabelPanelPanelSettingsBrightness, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelPanelSettingsBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelPanelSettingsBrightness, &ui_font_FontKoHoMiniBold14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderPanelPanelSettingsBrightness = lv_slider_create(ui_PanelPanelSettingsBrightness);
    lv_slider_set_value(ui_SliderPanelPanelSettingsBrightness, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderPanelPanelSettingsBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderPanelPanelSettingsBrightness, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderPanelPanelSettingsBrightness, 84);
    lv_obj_set_height(ui_SliderPanelPanelSettingsBrightness, 2);
    lv_obj_set_x(ui_SliderPanelPanelSettingsBrightness, 38);
    lv_obj_set_y(ui_SliderPanelPanelSettingsBrightness, 0);
    lv_obj_set_align(ui_SliderPanelPanelSettingsBrightness, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SliderPanelPanelSettingsBrightness, lv_color_hex(0x000000),
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPanelPanelSettingsBrightness, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderPanelPanelSettingsBrightness, lv_color_hex(0x000000),
                              LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPanelPanelSettingsBrightness, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_PanelPanelSettingsHue = lv_obj_create(ui_PanelCameraSettings);
    lv_obj_set_width(ui_PanelPanelSettingsHue, 172);
    lv_obj_set_height(ui_PanelPanelSettingsHue, 30);
    lv_obj_set_x(ui_PanelPanelSettingsHue, 0);
    lv_obj_set_y(ui_PanelPanelSettingsHue, 65);
    lv_obj_set_align(ui_PanelPanelSettingsHue, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPanelSettingsHue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelPanelSettingsHue, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPanelSettingsHue, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPanelSettingsHue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPanelSettingsHue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPanelSettingsHue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPanelSettingsHue, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_PanelPanelSettingsHue, 100, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelPanelPanelSettingsHue = lv_label_create(ui_PanelPanelSettingsHue);
    lv_obj_set_width(ui_LabelPanelPanelSettingsHue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelPanelSettingsHue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelPanelSettingsHue, -49);
    lv_obj_set_y(ui_LabelPanelPanelSettingsHue, 0);
    lv_obj_set_align(ui_LabelPanelPanelSettingsHue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelPanelSettingsHue, "Hue");
    lv_obj_set_style_text_color(ui_LabelPanelPanelSettingsHue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPanelPanelSettingsHue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPanelPanelSettingsHue, &ui_font_FontKoHoMiniBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderPanelPanelSettingsHue = lv_slider_create(ui_PanelPanelSettingsHue);
    lv_slider_set_value(ui_SliderPanelPanelSettingsHue, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderPanelPanelSettingsHue) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderPanelPanelSettingsHue, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderPanelPanelSettingsHue, 84);
    lv_obj_set_height(ui_SliderPanelPanelSettingsHue, 2);
    lv_obj_set_x(ui_SliderPanelPanelSettingsHue, 38);
    lv_obj_set_y(ui_SliderPanelPanelSettingsHue, 0);
    lv_obj_set_align(ui_SliderPanelPanelSettingsHue, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SliderPanelPanelSettingsHue, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPanelPanelSettingsHue, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderPanelPanelSettingsHue, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPanelPanelSettingsHue, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

}
