// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: esp32_p4_eye_factory

#include "../ui.h"

void ui_ScreenPicSave_screen_init(void)
{
    ui_ScreenPicSave = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPicSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageScreenPicSaveAlbum = lv_img_create(ui_ScreenPicSave);
    lv_img_set_src(ui_ImageScreenPicSaveAlbum, &ui_img_album_big_png);
    lv_obj_set_width(ui_ImageScreenPicSaveAlbum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageScreenPicSaveAlbum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageScreenPicSaveAlbum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageScreenPicSaveAlbum, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageScreenPicSaveAlbum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageScreenPicSaveCamera = lv_img_create(ui_ScreenPicSave);
    lv_img_set_src(ui_ImageScreenPicSaveCamera, &ui_img_camera_big_png);
    lv_obj_set_width(ui_ImageScreenPicSaveCamera, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageScreenPicSaveCamera, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageScreenPicSaveCamera, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageScreenPicSaveCamera, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageScreenPicSaveCamera, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageScreenPicSaveIntervalCam = lv_img_create(ui_ScreenPicSave);
    lv_img_set_src(ui_ImageScreenPicSaveIntervalCam, &ui_img_interval_big_png);
    lv_obj_set_width(ui_ImageScreenPicSaveIntervalCam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageScreenPicSaveIntervalCam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageScreenPicSaveIntervalCam, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageScreenPicSaveIntervalCam, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageScreenPicSaveIntervalCam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageScreenPicSaveVideoMode = lv_img_create(ui_ScreenPicSave);
    lv_img_set_src(ui_ImageScreenPicSaveVideoMode, &ui_img_video_big_png);
    lv_obj_set_width(ui_ImageScreenPicSaveVideoMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageScreenPicSaveVideoMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageScreenPicSaveVideoMode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageScreenPicSaveVideoMode, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageScreenPicSaveVideoMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageScreenPicSaveUSB = lv_img_create(ui_ScreenPicSave);
    lv_img_set_src(ui_ImageScreenPicSaveUSB, &ui_img_usb_big_png);
    lv_obj_set_width(ui_ImageScreenPicSaveUSB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageScreenPicSaveUSB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageScreenPicSaveUSB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageScreenPicSaveUSB, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageScreenPicSaveUSB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageScreenPicSaveSetting = lv_img_create(ui_ScreenPicSave);
    lv_img_set_src(ui_ImageScreenPicSaveSetting, &ui_img_settings_big_png);
    lv_obj_set_width(ui_ImageScreenPicSaveSetting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageScreenPicSaveSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageScreenPicSaveSetting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageScreenPicSaveSetting, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageScreenPicSaveSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
