// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: Camera

#ifndef _CAMERA_UI_H
#define _CAMERA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "esp_brookesia.h"
#include "ui_events.h"
// SCREEN: ui_ScreenCameraShot
void ui_ScreenCameraShot_screen_init(void);
extern lv_obj_t *ui_ScreenCameraShot;
extern lv_obj_t *ui_PanelCameraShotTitle;
extern lv_obj_t *ui_LabelCameraShotTitle;
extern lv_obj_t *ui_ImageCameraShotImage;
extern lv_obj_t *ui_PanelCameraShotControl;
extern lv_obj_t *ui_PanelCameraShotControlBg;
extern lv_obj_t *ui_ButtonCameraShotBtn;
void ui_event_PanelCameraShotAlbum( lv_event_t * e);
extern lv_obj_t *ui_PanelCameraShotAlbum;
// SCREEN: ui_ScreenCameraPhoto
void ui_ScreenCameraPhoto_screen_init(void);
void ui_event_ScreenCameraPhoto( lv_event_t * e);
extern lv_obj_t *ui_ScreenCameraPhoto;
extern lv_obj_t *ui_PanelCameraPhotoTitle;
extern lv_obj_t *ui_LabelCameraPhotoTitle;
extern lv_obj_t *ui_ImageCameraPhotoImage;




void ui_camera_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
