.. toctree::
    :hidden:
    :caption: {IDF_TARGET_NAME} Boards

    ESP32-P4-Function-EV-Board <esp32-p4-function-ev-board/index>

=============================   ===========================
      **{IDF_TARGET_NAME} Development Boards**
-----------------------------------------------------------
|ESP32-P4-Function-EV-Board|_
-----------------------------   ---------------------------
`ESP32-P4-Function-EV-Board`_
=============================   ===========================

.. |ESP32-P4-Function-EV-Board| image:: ../_static/esp32-p4-function-ev-board/esp32-p4-function-ev-board-isometric.png
.. _ESP32-P4-Function-EV-Board: esp32-p4-function-ev-board/index.html
