.. toctree::
    :hidden:
    :caption: {IDF_TARGET_NAME} Boards

    ESP32-P4X-Function-EV-Board <esp32-p4x-function-ev-board/index>
    SP32-P4X-C5-Function-EV-Board <esp32-p4x-c5-function-ev-board/index>
    ESP32-P4X-EYE <esp32-p4x-eye/index>
    EOL (End of Life) Boards <eol/eol-boards>

==================================   ==============================
      **{IDF_TARGET_NAME} Boards**
-------------------------------------------------------------------
|ESP32-P4X-Function-EV-Board|_          |ESP32-P4X-EYE|_
----------------------------------   ------------------------------
`ESP32-P4X-Function-EV-Board`_          `ESP32-P4X-EYE`_
----------------------------------   ------------------------------
|ESP32-P4X-C5-Function-EV-Board|_
----------------------------------   ------------------------------
`ESP32-P4X-C5-Function-EV-Board`_
==================================   ==============================

.. |ESP32-P4X-Function-EV-Board| image:: ../_static/esp32-p4x-function-ev-board/esp32-p4x-function-ev-board-isometric_v1.6.png
.. _ESP32-P4X-Function-EV-Board: esp32-p4x-function-ev-board/index.html

.. |ESP32-P4X-EYE| image:: ../_static/esp32-p4-eye/pic_product_esp32_p4_eye_back.png
.. _ESP32-P4X-EYE: esp32-p4x-eye/index.html

.. |ESP32-P4X-C5-Function-EV-Board| image:: ../_static/esp32-p4x-c5-function-ev-board/esp32-p4x-c5-function-ev-board-isometric.png
.. _ESP32-P4X-C5-Function-EV-Board: esp32-p4x-c5-function-ev-board/index.html
