.. toctree::
    :hidden:
    :caption: {IDF_TARGET_NAME} Boards

    ESP32-H2-DevKitM-1 <esp32-h2-devkitm-1/index>


============================   ===========================
      **{IDF_TARGET_NAME} Development Boards**
----------------------------------------------------------
|ESP32-H2-DevKitM-1|_
----------------------------   ---------------------------
`ESP32-H2-DevKitM-1`_
============================   ===========================

.. |ESP32-H2-DevKitM-1| image:: ../_static/esp32-h2-devkitm-1/esp32-h2-devkitm-1-45.png
.. _ESP32-H2-DevKitM-1: esp32-h2-devkitm-1/index.html
